// Dev Mode Configuration
// Enables quick access to all dashboards without authentication

export const DEV_MODE = true; // Set to false in production

export const DEV_ACCOUNTS = {
  'college-coach': {
    id: 'dev-user-college-coach',
    email: 'coach@college.dev',
    role: 'coach' as const,
    coachProfile: {
      id: 'dev-coach-college',
      user_id: 'dev-user-college-coach',
      full_name: 'Mike Davis',
      school_name: 'Texas A&M University',
      division: 'D1',
      conference: 'SEC',
      title: 'Head Coach',
      phone: '555-0101',
      avatar_url: null,
      logo_url: null,
      coach_type: 'college' as const,
    }
  },
  'high-school-coach': {
    id: 'dev-user-hs-coach',
    email: 'coach@highschool.dev',
    role: 'coach' as const,
    coachProfile: {
      id: 'dev-coach-hs',
      user_id: 'dev-user-hs-coach',
      full_name: 'John Smith',
      school_name: 'Lincoln High School',
      division: null,
      conference: null,
      title: 'Head Coach',
      phone: '555-0102',
      avatar_url: null,
      logo_url: null,
      coach_type: 'high_school' as const,
    }
  },
  'juco-coach': {
    id: 'dev-user-juco-coach',
    email: 'coach@juco.dev',
    role: 'coach' as const,
    coachProfile: {
      id: 'dev-coach-juco',
      user_id: 'dev-user-juco-coach',
      full_name: 'Bob Johnson',
      school_name: 'Central Community College',
      division: 'JUCO',
      conference: 'NJCAA',
      title: 'Head Coach',
      phone: '555-0103',
      avatar_url: null,
      logo_url: null,
      coach_type: 'juco' as const,
    }
  },
  'showcase-coach': {
    id: 'dev-user-showcase-coach',
    email: 'coach@showcase.dev',
    role: 'coach' as const,
    coachProfile: {
      id: 'dev-coach-showcase',
      user_id: 'dev-user-showcase-coach',
      full_name: 'Sarah Williams',
      school_name: 'Elite Baseball Academy',
      division: null,
      conference: null,
      title: 'Director',
      phone: '555-0104',
      avatar_url: null,
      logo_url: null,
      coach_type: 'showcase' as const,
    }
  },
  'player-hs': {
    id: 'dev-user-player-hs',
    email: 'player@highschool.dev',
    role: 'player' as const,
    playerProfile: {
      id: 'dev-player-hs',
      user_id: 'dev-user-player-hs',
      first_name: 'Jake',
      last_name: 'Anderson',
      email: 'player@highschool.dev',
      phone: '555-0201',
      primary_position: 'SS',
      secondary_position: 'OF',
      grad_year: 2025,
      bats: 'R',
      throws: 'R',
      height_feet: 6,
      height_inches: 1,
      weight_lbs: 185,
      city: 'Austin',
      state: 'TX',
      high_school_name: 'Westlake High School',
      club_team: 'Texas Prospects',
      gpa: 3.8,
      sat_score: 1320,
      pitch_velo: null,
      exit_velo: 94,
      sixty_time: 6.7,
      pop_time: null,
      recruiting_activated: true,
      recruiting_activated_at: new Date().toISOString(),
      avatar_url: null,
      player_type: 'high_school' as const,
    }
  },
  'player-showcase': {
    id: 'dev-user-player-showcase',
    email: 'player@showcase.dev',
    role: 'player' as const,
    playerProfile: {
      id: 'dev-player-showcase',
      user_id: 'dev-user-player-showcase',
      first_name: 'Marcus',
      last_name: 'Rodriguez',
      email: 'player@showcase.dev',
      phone: '555-0202',
      primary_position: 'P',
      secondary_position: '1B',
      grad_year: 2026,
      bats: 'L',
      throws: 'L',
      height_feet: 6,
      height_inches: 3,
      weight_lbs: 195,
      city: 'San Diego',
      state: 'CA',
      high_school_name: 'Cathedral High School',
      club_team: 'SoCal Elite',
      gpa: 3.5,
      sat_score: 1250,
      pitch_velo: 91,
      exit_velo: 89,
      sixty_time: 7.1,
      pop_time: null,
      recruiting_activated: true,
      recruiting_activated_at: new Date().toISOString(),
      avatar_url: null,
      player_type: 'showcase' as const,
    }
  },
  'player-juco': {
    id: 'dev-user-player-juco',
    email: 'player@juco.dev',
    role: 'player' as const,
    playerProfile: {
      id: 'dev-player-juco',
      user_id: 'dev-user-player-juco',
      first_name: 'Tyler',
      last_name: 'Martinez',
      email: 'player@juco.dev',
      phone: '555-0203',
      primary_position: 'C',
      secondary_position: null,
      grad_year: 2024,
      bats: 'R',
      throws: 'R',
      height_feet: 5,
      height_inches: 11,
      weight_lbs: 200,
      city: 'Phoenix',
      state: 'AZ',
      high_school_name: null,
      club_team: null,
      gpa: 3.2,
      sat_score: null,
      pitch_velo: null,
      exit_velo: 92,
      sixty_time: 7.3,
      pop_time: 1.95,
      recruiting_activated: true,
      recruiting_activated_at: new Date().toISOString(),
      avatar_url: null,
      player_type: 'juco' as const,
    }
  },
  'player-college': {
    id: 'dev-user-player-college',
    email: 'player@college.dev',
    role: 'player' as const,
    playerProfile: {
      id: 'dev-player-college',
      user_id: 'dev-user-player-college',
      first_name: 'Chris',
      last_name: 'Thompson',
      email: 'player@college.dev',
      phone: '555-0204',
      primary_position: 'OF',
      secondary_position: null,
      grad_year: 2023,
      bats: 'L',
      throws: 'L',
      height_feet: 6,
      height_inches: 0,
      weight_lbs: 180,
      city: 'Atlanta',
      state: 'GA',
      high_school_name: null,
      club_team: null,
      gpa: 3.4,
      sat_score: null,
      pitch_velo: null,
      exit_velo: 95,
      sixty_time: 6.5,
      pop_time: null,
      recruiting_activated: false,
      recruiting_activated_at: null,
      avatar_url: null,
      player_type: 'college' as const,
    }
  },
};

export type DevAccountType = keyof typeof DEV_ACCOUNTS;

export function getDevAccount(type: DevAccountType) {
  return DEV_ACCOUNTS[type];
}

export function isDevMode() {
  return DEV_MODE && process.env.NODE_ENV === 'development';
}
