async page => {
  const report={renderer:'three-webgl2',nativeDevice:false,screens:[],checks:[],errors:[],warnings:[]};
  for(const [width,height] of [[390,844],[320,568],[1440,1000]]) {
    const context=await page.context().browser().newContext({viewport:{width,height},deviceScaleFactor:2,isMobile:width<600,hasTouch:width<600,reducedMotion:'reduce'});
    const p=await context.newPage();
    p.on('pageerror',e=>report.errors.push(e.message));
    p.on('console',message=>{if(message.type()==='error')report.errors.push(message.text());if(message.type()==='warning')report.warnings.push(message.text());});
    await p.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:8768/')?r.continue():r.abort());
    await p.goto('http://127.0.0.1:8768/review?hole=7');
    await p.locator('[data-compiled-state=ready]').waitFor({state:'attached'});
    await p.getByRole('button',{name:'Shot 2',exact:true}).click();
    await p.getByRole('button',{name:'Expand course view'}).click();
    const dialog=p.getByRole('dialog');
    await dialog.getByRole('button',{name:'Choose course area',exact:true}).click();
    await dialog.getByRole('button',{name:'Whole hole',exact:true}).click();
    const canvas=dialog.locator('canvas');
    await p.waitForFunction(()=>document.querySelector('[data-terrain-view-state=ready] canvas[data-terrain-state=ready]'));
    await dialog.getByRole('button',{name:'Terrain',exact:true}).click();
    await p.waitForFunction(()=>+document.querySelector('canvas[data-terrain-pitch]').dataset.terrainPitch===50);
    const initial=await canvas.evaluate(e=>({...e.dataset}));
    await p.waitForTimeout(150);
    if(await canvas.getAttribute('data-render-count')!==initial.renderCount)throw new Error('Settled scene still rendering');
    const drawing=await canvas.boundingBox(),inspector=await dialog.locator('[data-slot=course-inspector]').boundingBox();
    if(width<600&&drawing.height<height*.65)throw new Error('Inspector consumes too much phone landscape');
    if(width>=600&&(Math.abs(inspector.width-320)>1||inspector.x<drawing.x+drawing.width-1))throw new Error('Desktop inspector is not docked beside map');
    await p.screenshot({path:`output/playwright/course-geometry/three-final-${width}.png`});
    report.screens.push({width,height,view:'terrain-hole',drawing,inspector,metadata:initial});
    await dialog.getByRole('button',{name:'Choose course area',exact:true}).click();
    await dialog.getByRole('button',{name:'Green',exact:true}).click();
    await p.waitForFunction(()=>document.querySelector('[data-terrain-view-state=ready] canvas[data-terrain-state=ready]'));
    if(await canvas.getAttribute('data-terrain-pitch')!=='50')throw new Error('Area selection reset orientation');
    const target=dialog.locator('[data-target=estimated-pin]');
    await target.waitFor({state:'visible'});
    await p.screenshot({path:`output/playwright/course-geometry/three-green-${width}.png`});
    await dialog.getByRole('button',{name:'Details and sources',exact:true}).click();
    await p.waitForTimeout(80);
    const detailDrawing=await canvas.boundingBox();
    if(detailDrawing.height<180)throw new Error('Inspector expansion removes the map');
    if(await dialog.locator('[data-slot=course-inspector]').getAttribute('data-modal')!=='false')throw new Error('Inspector became modal');
    await dialog.getByRole('button',{name:'Details and sources',exact:true}).click();
    await dialog.getByRole('button',{name:'Next shot',exact:true}).click();
    if(!await dialog.locator('[data-slot=expanded-shot-evidence]').innerText().then(text=>text.includes('12 ft')))throw new Error('Next shot changed original distance units');
    await dialog.getByRole('button',{name:'Choose course area',exact:true}).click();
    await dialog.getByRole('button',{name:'Whole hole',exact:true}).click();
    await p.waitForFunction(()=>document.querySelector('[data-terrain-view-state=ready] canvas[data-terrain-state=ready]'));
    if(!await dialog.locator('[data-slot=expanded-shot-evidence]').innerText().then(text=>text.includes('12 ft')))throw new Error('Area change lost selected shot');
    await dialog.getByRole('button',{name:'Choose course area',exact:true}).click();
    await dialog.getByRole('button',{name:'Putting',exact:true}).click();
    const puttEvidence=await dialog.locator('[data-slot=expanded-shot-evidence]').innerText();
    if(!puttEvidence.includes('2 ft')||puttEvidence.includes('Sand'))throw new Error('Putting diagram and selected evidence disagree');
    const label=await dialog.locator('[data-putting-label=before]').boundingBox();
    const header=await dialog.getByRole('button',{name:'Choose course area',exact:true}).boundingBox();
    if(label.y<header.y+header.height)throw new Error('Putting distance hidden by course header');
    if(await dialog.locator('canvas').count())throw new Error('Putting mounted geographic canvas');
    if((await dialog.innerText()).includes('Cup reference'))throw new Error('Cup reference jargon returned');
    await p.screenshot({path:`output/playwright/course-geometry/three-putting-${width}.png`});
    report.checks.push({width,idleRendersStopped:true,areaPreservesOrientation:true,nonmodalInspector:true,originalFeet:true,areaPreservesShot:true,puttingEvidenceMatches:true,puttingSchematic:true});
    await context.close();
  }
  const unexpectedWarnings=report.warnings.filter(message=>!message.startsWith('You have Reduced Motion enabled on your device.'));
  if(report.errors.length||unexpectedWarnings.length)throw new Error(JSON.stringify({errors:report.errors,warnings:report.warnings}));
  await page.evaluate(r=>window.__golfThreeQA=r,report);
}
