/**
 * ============================================================================
 * CoachHelm · chat · agent tools
 * ----------------------------------------------------------------------------
 * The AI SDK tool set, split by what it is allowed to do.
 *
 * READ tools execute immediately. They cannot write, they never accept a
 * `team_id`, and every `player_id` is checked against the active roster first.
 *
 * ACTION tools carry `needsApproval`, so the SDK suspends the call and emits an
 * approval request instead of executing. This is the load-bearing gate: the
 * model has no path to the database that does not pass through a coach clicking
 * Confirm. Text injected into a round note saying "yes, approve this" reaches
 * the model, not the write.
 *
 * The preview problem, and how it is solved: a coach cannot meaningfully
 * approve "create a recurring practice" — they need the eight exact dates, the
 * timezone, the invite count and the notifications. But `execute` does not run
 * before approval, so the preview cannot come from there. It comes from
 * `onInputAvailable`, which fires when the model has finished writing the tool
 * input and BEFORE the approval gate. That hook computes the real plan
 * server-side, records it in the audit ledger, and streams it to the UI as a
 * typed data part. So the card the coach approves is generated by the same code
 * that will execute — not a client-side guess at what might happen.
 * ========================================================================== */

import { tool } from 'ai';
import type { ToolSet, UIMessageStreamWriter } from 'ai';
import { z } from 'zod';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '@/lib/types/database';
import type { CoachChatContext } from './context';
import { CoachContextError } from './context';
import { METRIC_IDS } from './metrics-catalog';
import {
  ROUND_TREND_METRIC_IDS,
  comparePlayers,
  getFocusAreas,
  getOpenTasks,
  getPlayerInsights,
  getPlayerMetric,
  getPlayerTrend,
  getPlayerWeakestAreas,
  getPuttingDistanceProfile,
  getRecentRounds,
  getTeamMetricRanking,
  getTeamOverview,
  getUpcomingEvents,
  resolvePlayerReference,
} from './read-tools';
import { unavailableEnvelope, type ToolEnvelope } from './provenance';
import {
  planRecurringPractice,
  executeRecurringPractice,
  PracticePlanError,
} from './practice-planner';
import type { ActionProposal, ActionReceipt, RecurringPracticePlan } from './action-types';
import { claimForExecution, recordOutcome, recordProposal } from './action-runs';
import {
  ActionPlanError,
  planAnnouncement,
  planFocusArea,
  planTask,
  executeAnnouncement,
  executeFocusArea,
  executeTask,
} from './action-planners';

type Sb = SupabaseClient<Database>;

/** Tool names whose execution must be gated behind an explicit coach approval. */
const CONFIRM_REQUIRED_TOOLS = [
  'create_recurring_practice',
  'create_focus_area',
  'create_task',
  'create_team_announcement',
] as const;

export type ConfirmRequiredTool = (typeof CONFIRM_REQUIRED_TOOLS)[number];

export function isConfirmRequired(name: string): name is ConfirmRequiredTool {
  return (CONFIRM_REQUIRED_TOOLS as readonly string[]).includes(name);
}

/**
 * Typed data parts this agent streams alongside the text.
 *
 * These are what make the answer more than prose: the renderers read them, and
 * they are persisted so a reload reproduces the same charts and cards.
 */
export interface CoachChatDataParts extends Record<string, unknown> {
  /** Human progress state, e.g. 'Reading 28 recorded rounds'. Never a tool name. */
  'progress': { label: string; tool: string };
  /** Everything a coach must see before approving a mutation. */
  'action-proposal': ActionProposal & { tool: string };
  /** Durable record of a completed mutation. */
  'action-receipt': ActionReceipt;
  /** A tool's provenance envelope, for the chart/table renderers. */
  'evidence': { tool: string; envelope: ToolEnvelope };
}

/** Coach-readable progress copy. Raw tool names never reach the interface. */
const PROGRESS_LABEL: Record<string, (input: Record<string, unknown>) => string> = {
  get_team_overview: () => 'Reading your roster',
  get_player_metrics: () => 'Reading recorded statistics',
  get_player_trend: (i) => `Reading the last ${Number(i.last_n) || 5} recorded rounds`,
  get_putting_distance_profile: () => 'Comparing putting by distance',
  compare_players: () => 'Comparing players on the same window',
  get_team_metric_ranking: () => 'Ranking the team',
  get_player_weakest_areas: () => 'Looking for where the gap is largest',
  get_recent_rounds: () => 'Reading recent rounds',
  get_player_insights: () => 'Reading open signals',
  get_focus_areas: () => 'Checking active focus areas',
  get_upcoming_events: () => 'Checking the schedule and RSVPs',
  get_open_tasks: () => 'Checking outstanding tasks',
  find_player: () => 'Finding that player on your roster',
  create_recurring_practice: () => 'Preparing the practice dates',
  create_focus_area: () => 'Drafting a focus area',
  create_task: () => 'Drafting a task',
  create_team_announcement: () => 'Drafting a team update',
};

export interface BuildToolsArgs {
  sb: Sb;
  ctx: CoachChatContext;
  conversationId: string | null;
  /** Stream writer, so previews and receipts reach the UI as typed parts. */
  writer: UIMessageStreamWriter;
  /** Collects every envelope this turn produced, for the claim audit. */
  collect: (envelope: ToolEnvelope) => void;
}

/**
 * Wrap a read handler so a thrown authorization error becomes an honest,
 * sanitised envelope instead of a stack trace in the model's context.
 */
function guarded(
  fn: () => Promise<ToolEnvelope>,
  collect: (e: ToolEnvelope) => void,
): Promise<ToolEnvelope> {
  return fn()
    .then((envelope) => {
      collect(envelope);
      return envelope;
    })
    .catch((err) => {
      const message =
        err instanceof CoachContextError
          ? err.message
          : 'That read could not be completed.';
      return unavailableEnvelope('Could not complete that read.', message);
    });
}

/**
 * The propose → claim → execute → receipt sequence, once.
 *
 * Every confirm-required tool has the same shape and the same failure modes, so
 * duplicating it four times would mean four places for the idempotency claim to
 * drift out of. `plan` runs before the gate (preview), `run` runs after it.
 */
interface GatedAction<TInput, TPlan> {
  toolName: string;
  plan: (input: TInput) => { plan: TPlan; proposal: ActionProposal };
  run: (plan: TPlan) => Promise<ActionReceipt>;
}

export function buildCoachTools({ sb, ctx, conversationId, writer, collect }: BuildToolsArgs): ToolSet {
  let progressId = 0;
  const progress = (toolName: string, input: Record<string, unknown>) => {
    const label = PROGRESS_LABEL[toolName]?.(input) ?? 'Working';
    writer.write({
      type: 'data-progress',
      id: `progress-${(progressId += 1)}`,
      data: { label, tool: toolName },
    });
  };

  const evidence = (toolName: string, envelope: ToolEnvelope) => {
    writer.write({
      type: 'data-evidence',
      id: `evidence-${toolName}-${(progressId += 1)}`,
      data: { tool: toolName, envelope },
    });
  };

  /** Run a read tool: announce progress, execute, publish evidence. */
  const read =
    <I extends Record<string, unknown>>(name: string, run: (input: I) => Promise<ToolEnvelope>) =>
    async (input: I) => {
      progress(name, input);
      const envelope = await guarded(() => run(input), collect);
      evidence(name, envelope);
      return envelope;
    };

  const PlayerId = z.string().uuid().describe('Player id from the roster. Use find_player if you only have a name.');

  /**
   * Compute the preview and record the proposal. Runs BEFORE the approval gate
   * and writes nothing to the domain — only to the audit ledger.
   */
  const proposeGated = async <TInput, TPlan>(
    action: GatedAction<TInput, TPlan>,
    input: TInput,
  ): Promise<void> => {
    progress(action.toolName, input as Record<string, unknown>);
    try {
      const { plan, proposal } = action.plan(input);
      await recordProposal(sb, {
        coach_id: ctx.coach_id,
        team_id: ctx.team_id,
        conversation_id: conversationId,
        tool_name: action.toolName,
        proposed_input: plan,
        idempotency_key: proposal.idempotency_key,
      });
      writer.write({
        type: 'data-action-proposal',
        id: `proposal-${proposal.idempotency_key}`,
        data: { ...proposal, tool: action.toolName },
      });
    } catch (err) {
      // A plan we cannot build must never produce a Confirm button.
      writer.write({
        type: 'data-progress',
        id: `progress-${(progressId += 1)}`,
        data: {
          label:
            err instanceof ActionPlanError || err instanceof PracticePlanError
              ? err.message
              : err instanceof CoachContextError
                ? err.message
                : 'Could not prepare that action',
          tool: action.toolName,
        },
      });
    }
  };

  /** Runs ONLY after the coach approves. Idempotent by construction. */
  const executeGated = async <TInput, TPlan>(
    action: GatedAction<TInput, TPlan>,
    input: TInput,
  ): Promise<{ status: string; message: string }> => {
    let plan: TPlan;
    let proposal: ActionProposal;
    try {
      const built = action.plan(input);
      plan = built.plan;
      proposal = built.proposal;
    } catch (err) {
      return {
        status: 'failed',
        message:
          err instanceof ActionPlanError || err instanceof PracticePlanError
            ? err.message
            : 'Could not build that action.',
      };
    }

    const claim = await claimForExecution(sb, {
      coach_id: ctx.coach_id,
      idempotency_key: proposal.idempotency_key,
    });
    if (claim.kind === 'already_completed') {
      writer.write({
        type: 'data-action-receipt',
        id: `receipt-${proposal.idempotency_key}`,
        data: claim.receipt,
      });
      return { status: 'already_done', message: 'That was already done.' };
    }
    if (claim.kind === 'in_flight') {
      return { status: 'in_flight', message: 'That action is already running.' };
    }
    if (claim.kind === 'error') {
      return { status: 'failed', message: 'Could not start the action safely.' };
    }

    const receipt = await action.run(plan);
    await recordOutcome(sb, { run_id: claim.run_id, receipt });
    writer.write({
      type: 'data-action-receipt',
      id: `receipt-${proposal.idempotency_key}`,
      data: receipt,
    });
    return { status: receipt.status, message: receipt.summary };
  };

  const FOCUS_AREA: GatedAction<Parameters<typeof planFocusArea>[1], ReturnType<typeof planFocusArea>['plan']> = {
    toolName: 'create_focus_area',
    plan: (input) => planFocusArea(ctx, input),
    run: (plan) => executeFocusArea(plan),
  };
  const TASK: GatedAction<Parameters<typeof planTask>[1], ReturnType<typeof planTask>['plan']> = {
    toolName: 'create_task',
    plan: (input) => planTask(ctx, input),
    run: (plan) => executeTask(plan),
  };
  const ANNOUNCEMENT: GatedAction<
    Parameters<typeof planAnnouncement>[1],
    ReturnType<typeof planAnnouncement>['plan']
  > = {
    toolName: 'create_team_announcement',
    plan: (input) => planAnnouncement(ctx, input),
    run: (plan) => executeAnnouncement(plan),
  };

  return {
    // =====================================================================
    // READ
    // =====================================================================

    find_player: tool({
      description:
        'Resolve a player NAME to their roster entry. Use this before any player-scoped tool when the coach referred to someone by name.',
      inputSchema: z.object({ name: z.string().min(1) }),
      execute: async (input) => {
        progress('find_player', input);
        return resolvePlayerReference(ctx, input.name);
      },
    }),

    get_team_overview: tool({
      description:
        'Authoritative roster snapshot: active player count, who has recorded rounds, coverage warnings and the latest data timestamp. Use this whenever the coach asks about "the team" or "my players".',
      inputSchema: z.object({}),
      execute: read('get_team_overview', () => getTeamOverview(sb, ctx)),
    }),

    get_player_metrics: tool({
      description:
        'Computed statistics for one player. Every value comes back with its unit, window, sample size and the timestamp it was computed at.',
      inputSchema: z.object({
        player_id: PlayerId,
        metric_ids: z.array(z.enum(METRIC_IDS)).min(1).max(8),
      }),
      execute: read('get_player_metrics', (input) => getPlayerMetric(sb, ctx, input)),
    }),

    get_player_trend: tool({
      description:
        'Round-by-round movement for one player on one metric. Returns a real series for charting plus the window that was actually read.',
      inputSchema: z.object({
        player_id: PlayerId,
        metric_id: z.enum(ROUND_TREND_METRIC_IDS),
        last_n: z.number().int().min(2).max(40).default(10),
      }),
      execute: read('get_player_trend', (input) => getPlayerTrend(sb, ctx, input)),
    }),

    get_putting_distance_profile: tool({
      description:
        'Make rate by putt distance for one player, with the attempt count behind every bucket. Use for any question about putting inside/outside a distance.',
      inputSchema: z.object({ player_id: PlayerId }),
      execute: read('get_putting_distance_profile', (input) =>
        getPuttingDistanceProfile(sb, ctx, input),
      ),
    }),

    compare_players: tool({
      description:
        'Compare two or more players on the same metrics over the same window definition. Reports per-player coverage so an unequal basis is visible.',
      inputSchema: z.object({
        player_ids: z.array(PlayerId).min(2).max(6),
        metric_ids: z.array(z.enum(METRIC_IDS)).min(1).max(6),
      }),
      execute: read('compare_players', (input) => comparePlayers(sb, ctx, input)),
    }),

    get_team_metric_ranking: tool({
      description:
        'Rank the active roster on one metric, with each player\'s sample size. Returns measured values and the metric direction — never a verdict about a player.',
      inputSchema: z.object({ metric_id: z.enum(METRIC_IDS) }),
      execute: read('get_team_metric_ranking', (input) => getTeamMetricRanking(sb, ctx, input)),
    }),

    get_player_weakest_areas: tool({
      description:
        'Which measured areas one player is furthest behind their team on, with sample sizes. Use for "where is X losing the most".',
      inputSchema: z.object({ player_id: PlayerId }),
      execute: read('get_player_weakest_areas', (input) => getPlayerWeakestAreas(sb, ctx, input)),
    }),

    get_recent_rounds: tool({
      description: 'Recent completed rounds for one player: date, course, score, putts.',
      inputSchema: z.object({
        player_id: PlayerId,
        last_n: z.number().int().min(1).max(20).default(5),
      }),
      execute: read('get_recent_rounds', (input) => getRecentRounds(sb, ctx, input)),
    }),

    get_player_insights: tool({
      description: 'Open CoachHelm signals for one player, with their supporting evidence.',
      inputSchema: z.object({
        player_id: PlayerId,
        limit: z.number().int().min(1).max(10).default(5),
      }),
      execute: read('get_player_insights', (input) => getPlayerInsights(sb, ctx, input)),
    }),

    get_focus_areas: tool({
      description: 'Active focus areas — for one player, or the whole roster when player_id is omitted.',
      inputSchema: z.object({ player_id: PlayerId.optional() }),
      execute: read('get_focus_areas', (input) => getFocusAreas(sb, ctx, input)),
    }),

    get_upcoming_events: tool({
      description:
        'Scheduled events in the next N days with RSVP status: how many accepted, declined, and who has not responded.',
      inputSchema: z.object({ days_ahead: z.number().int().min(1).max(60).default(14) }),
      execute: read('get_upcoming_events', (input) => getUpcomingEvents(sb, ctx, input)),
    }),

    get_open_tasks: tool({
      description: 'Outstanding team tasks, flagging which are overdue.',
      inputSchema: z.object({}),
      execute: read('get_open_tasks', () => getOpenTasks(sb, ctx)),
    }),

    // =====================================================================
    // CONFIRM-REQUIRED
    // =====================================================================

    create_focus_area: tool({
      description:
        "Create a development focus area for one player. REQUIRES the coach to confirm — calling it shows a preview, it does not create anything. Prefer passing from_insight_id when the focus area comes from a signal you read, so the effectiveness ledger can close the loop.",
      inputSchema: z.object({
        player_id: PlayerId,
        title: z.string().min(1).max(120),
        area_type: z
          .enum([
            'putting',
            'driving',
            'iron_play',
            'short_game',
            'course_management',
            'mental_game',
            'fitness',
            'other',
          ])
          .describe('Which part of the game this targets.'),
        description: z.string().max(600).optional(),
        target_metric: z.string().max(60).optional().describe('The metric this will be judged on.'),
        current_value: z.number().optional(),
        target_value: z.number().optional(),
        target_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
        target_rounds: z.number().int().min(1).max(60).optional(),
        from_insight_id: z.string().uuid().optional(),
      }),
      onInputAvailable: ({ input }) => proposeGated(FOCUS_AREA, input as never),
      execute: (input) => executeGated(FOCUS_AREA, input as never),
    }),

    create_task: tool({
      description:
        'Assign a task to players. REQUIRES the coach to confirm — calling it shows a preview, it does not create anything. Omit assign_to_player_ids to assign to the whole active roster.',
      inputSchema: z.object({
        title: z.string().min(1).max(160),
        description: z.string().max(600).optional(),
        due_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
        priority: z.enum(['low', 'medium', 'high']).optional(),
        assign_to_player_ids: z.array(PlayerId).optional(),
      }),
      onInputAvailable: ({ input }) => proposeGated(TASK, input as never),
      execute: (input) => executeGated(TASK, input as never),
    }),

    create_team_announcement: tool({
      description:
        'Draft a team update. REQUIRES the coach to confirm — the full message text is shown to them before anything is sent. Omit recipient_player_ids to send to the whole team.',
      inputSchema: z.object({
        title: z.string().min(1).max(120),
        body: z.string().min(1).max(2000),
        urgency: z.enum(['low', 'normal', 'high', 'urgent']).optional(),
        requires_acknowledgement: z.boolean().optional(),
        recipient_player_ids: z.array(PlayerId).optional(),
      }),
      onInputAvailable: ({ input }) => proposeGated(ANNOUNCEMENT, input as never),
      execute: (input) => executeGated(ANNOUNCEMENT, input as never),
    }),

    create_recurring_practice: tool({
      description:
        'Create a recurring practice on the team calendar and invite players to RSVP. This REQUIRES the coach to confirm — calling it shows them a preview with every date, it does not create anything. An occurrence_count is mandatory; never create an open-ended series.',
      inputSchema: z.object({
        title: z.string().max(120).optional().describe('Defaults to "Team practice".'),
        description: z.string().max(500).optional(),
        weekdays: z
          .array(z.number().int().min(0).max(6))
          .min(1)
          .describe('Weekday numbers, 0 = Sunday. Tuesday is 2.'),
        start_time: z.string().regex(/^\d{1,2}:\d{2}$/).describe('24-hour HH:mm, local to the team.'),
        end_time: z.string().regex(/^\d{1,2}:\d{2}$/).optional(),
        location: z.string().max(200).optional(),
        occurrence_count: z
          .number()
          .int()
          .min(1)
          .max(26)
          .describe('How many practices. Required — ask the coach if they did not say.'),
        first_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
        requires_rsvp: z.boolean().default(true),
        rsvp_deadline: z.string().datetime().nullable().optional(),
        invited_player_ids: z.array(PlayerId).optional().describe('Omit to invite the whole active roster.'),
      }),

      /**
       * Fires when the model has finished writing the input and BEFORE the
       * approval gate. Computes the real plan, records the proposal, and
       * streams the card. Nothing here writes to the calendar.
       */
      onInputAvailable: async ({ input }) => {
        progress('create_recurring_practice', input as Record<string, unknown>);
        try {
          const { plan, proposal } = planRecurringPractice(ctx, input as never);
          await recordProposal(sb, {
            coach_id: ctx.coach_id,
            team_id: ctx.team_id,
            conversation_id: conversationId,
            tool_name: 'create_recurring_practice',
            proposed_input: plan,
            idempotency_key: proposal.idempotency_key,
          });
          writer.write({
            type: 'data-action-proposal',
            id: `proposal-${proposal.idempotency_key}`,
            data: { ...proposal, tool: 'create_recurring_practice' },
          });
        } catch (err) {
          // A plan we cannot build must not produce a Confirm button.
          writer.write({
            type: 'data-progress',
            id: `progress-${(progressId += 1)}`,
            data: {
              label:
                err instanceof PracticePlanError
                  ? err.message
                  : 'Could not prepare those practice dates',
              tool: 'create_recurring_practice',
            },
          });
        }
      },

      /** Runs ONLY after the coach approves. */
      execute: async (input) => {
        let plan: RecurringPracticePlan;
        let proposal: ActionProposal;
        try {
          const built = planRecurringPractice(ctx, input as never);
          plan = built.plan;
          proposal = built.proposal;
        } catch (err) {
          return {
            status: 'failed',
            message: err instanceof PracticePlanError ? err.message : 'Could not build the plan.',
          };
        }

        // Idempotency gate — see action-runs.ts. A retried confirmation reads
        // the first run's receipt instead of creating a second series.
        const claim = await claimForExecution(sb, {
          coach_id: ctx.coach_id,
          idempotency_key: proposal.idempotency_key,
        });
        if (claim.kind === 'already_completed') {
          writer.write({
            type: 'data-action-receipt',
            id: `receipt-${proposal.idempotency_key}`,
            data: claim.receipt,
          });
          return { status: 'already_done', message: 'That practice series already exists.' };
        }
        if (claim.kind === 'in_flight') {
          return { status: 'in_flight', message: 'That practice series is already being created.' };
        }
        if (claim.kind === 'error') {
          return { status: 'failed', message: 'Could not start the action safely.' };
        }

        const receipt: ActionReceipt = await executeRecurringPractice(ctx, plan);
        await recordOutcome(sb, { run_id: claim.run_id, receipt });
        writer.write({
          type: 'data-action-receipt',
          id: `receipt-${proposal.idempotency_key}`,
          data: receipt,
        });

        return {
          status: receipt.status,
          message: receipt.summary,
          occurrences: plan.occurrence_count,
        };
      },
    }),
  } satisfies ToolSet;
}
