/**
 * ============================================================================
 * CoachHelm · chat · practice planner — the recurring-practice vertical slice
 * ----------------------------------------------------------------------------
 * "Create a recurring practice every Tuesday at 3:00 PM for the next eight
 * weeks and send it to all active players for RSVP by Monday at noon."
 *
 * Two functions, and the relationship between them is the whole design:
 *
 *   {@link planRecurringPractice}    resolves the plan and every occurrence
 *                                    date. Writes nothing.
 *   {@link executeRecurringPractice} runs the plan through the EXISTING
 *                                    `createRecurringEvent` server action.
 *
 * The dates the coach approves are generated by `generateOccurrences` from
 * `@/lib/golf/recurrence` — the same function `createRecurringEvent` uses to
 * materialise the series. So the preview is not a mock-up of what will happen;
 * it is the same computation, run early. If they could drift, the preview would
 * be a lie with a Confirm button under it.
 *
 * Nothing about recurrence, attendance fan-out, notification channels or
 * authorization is reimplemented here. That logic lives in the server action,
 * is already tested, and is called rather than copied.
 * ========================================================================== */

import { generateOccurrences, serializeRecurrenceRule } from '@/lib/golf/recurrence';
import type { CoachChatContext } from './context';
import type { ActionProposal, ActionReceipt, RecurringPracticePlan } from './action-types';

/** Hard ceiling on a single agent-created series. */
const MAX_OCCURRENCES = 26;

const WEEKDAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

export interface PlanPracticeInput {
  title?: string;
  description?: string;
  /** 0 = Sunday. At least one required. */
  weekdays: number[];
  /** `HH:mm`, local to the team's timezone. */
  start_time: string;
  end_time?: string;
  location?: string;
  /**
   * How many occurrences. REQUIRED — there is no "just keep going" path.
   * An unbounded series silently filling a calendar is not a thing a coach
   * should be able to trigger by phrasing a sentence loosely.
   */
  occurrence_count: number;
  /** ISO `YYYY-MM-DD`. Defaults to the next matching weekday from today. */
  first_date?: string;
  requires_rsvp?: boolean;
  /** ISO instant for the RSVP deadline, or null. */
  rsvp_deadline?: string | null;
  /** Omit to invite the whole active roster. */
  invited_player_ids?: string[];
}

export class PracticePlanError extends Error {}

/** Format an ISO date as the coach would read it, in the team's timezone. */
function humanDate(iso: string, timezone: string): string {
  const d = new Date(`${iso}T12:00:00Z`);
  return new Intl.DateTimeFormat('en-US', {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
    timeZone: timezone,
  }).format(d);
}

/** Format `HH:mm` as a coach reads it. */
function humanTime(hhmm: string): string {
  const [h = '0', m = '00'] = hhmm.split(':');
  const hour = Number(h);
  const suffix = hour >= 12 ? 'PM' : 'AM';
  const twelve = hour % 12 === 0 ? 12 : hour % 12;
  return `${twelve}:${m} ${suffix}`;
}

/** The next date on or after `from` that falls on one of `weekdays`. */
function nextMatchingDate(from: Date, weekdays: number[]): string {
  for (let i = 0; i < 14; i += 1) {
    const d = new Date(from.getTime() + i * 86400_000);
    if (weekdays.includes(d.getDay())) return d.toISOString().slice(0, 10);
  }
  return from.toISOString().slice(0, 10);
}

/**
 * Resolve a full plan and its exact occurrence dates. Writes nothing.
 *
 * `missing` is returned rather than thrown for things the coach can still
 * supply — a practice with no location is genuinely creatable, so we surface
 * the gap on the card instead of blocking. What IS thrown is anything that
 * would produce a wrong series: no weekday, no bound, a bad time.
 */
export function planRecurringPractice(
  ctx: CoachChatContext,
  input: PlanPracticeInput,
): { plan: RecurringPracticePlan; proposal: ActionProposal } {
  const weekdays = [...new Set(input.weekdays)].filter((d) => d >= 0 && d <= 6).sort();
  if (weekdays.length === 0) {
    throw new PracticePlanError('Which day of the week should the practice repeat on?');
  }
  if (!/^\d{1,2}:\d{2}$/.test(input.start_time)) {
    throw new PracticePlanError('What time should the practice start?');
  }
  if (!Number.isFinite(input.occurrence_count) || input.occurrence_count < 1) {
    throw new PracticePlanError(
      'How many weeks should this run for? A recurring practice always needs an end.',
    );
  }

  const count = Math.min(Math.round(input.occurrence_count), MAX_OCCURRENCES);
  const startDate = input.first_date ?? nextMatchingDate(new Date(), weekdays);

  // The SAME generator the create path uses. Preview and reality cannot drift.
  const rule = { frequency: 'weekly' as const, weekdays, count };
  const dates = generateOccurrences(startDate, rule, { maxOccurrences: count }).slice(0, count);
  if (dates.length === 0) {
    throw new PracticePlanError('That schedule produces no dates. Check the day and start date.');
  }

  const invitedIds =
    input.invited_player_ids && input.invited_player_ids.length > 0
      ? input.invited_player_ids.filter((id) => ctx.roster.some((p) => p.id === id))
      : ctx.roster.map((p) => p.id);
  const invitedNames = invitedIds
    .map((id) => ctx.roster.find((p) => p.id === id)?.name)
    .filter((n): n is string => Boolean(n));

  const requiresRsvp = input.requires_rsvp ?? true;
  const title = input.title?.trim() || 'Team practice';

  const plan: RecurringPracticePlan = {
    title,
    description: input.description?.trim() || null,
    timezone: ctx.timezone,
    start_date: dates[0]!,
    start_time: input.start_time,
    end_time: input.end_time ?? null,
    location: input.location?.trim() || null,
    weekdays,
    occurrence_count: dates.length,
    occurrence_dates: dates,
    requires_rsvp: requiresRsvp,
    rsvp_deadline: input.rsvp_deadline ?? null,
    invited_player_ids: invitedIds,
    invited_player_names: invitedNames,
  };

  const missing: string[] = [];
  if (!plan.location) missing.push('Location');

  const notifications = requiresRsvp
    ? [
        `An in-app invitation, email and push notification to ${invitedIds.length} player${invitedIds.length === 1 ? '' : 's'}`,
        'Each player is asked to RSVP',
      ]
    : [`An in-app notification, email and push notification to ${invitedIds.length} player${invitedIds.length === 1 ? '' : 's'}`];

  const dayLabel = weekdays.map((d) => WEEKDAY_NAMES[d]).join(' and ');
  const facts = [
    { label: 'Repeats', value: `Every ${dayLabel} at ${humanTime(plan.start_time)}` },
    {
      label: 'Dates',
      value: dates.map((d) => humanDate(d, ctx.timezone)).join(' · '),
    },
    { label: 'Occurrences', value: `${dates.length}` },
    { label: 'Timezone', value: ctx.timezone },
    {
      label: 'Location',
      value: plan.location ?? 'Not set',
      missing: !plan.location,
    },
    { label: 'Invites', value: `${invitedIds.length} active player${invitedIds.length === 1 ? '' : 's'}` },
    {
      label: 'RSVP',
      value: requiresRsvp
        ? plan.rsvp_deadline
          ? `Required by ${new Intl.DateTimeFormat('en-US', {
              weekday: 'short',
              month: 'short',
              day: 'numeric',
              hour: 'numeric',
              minute: '2-digit',
              timeZone: ctx.timezone,
            }).format(new Date(plan.rsvp_deadline))}`
          : 'Required, no deadline'
        : 'Not required',
    },
  ];

  return {
    plan,
    proposal: {
      action: 'Create a recurring practice',
      summary: `${dates.length} practices, every ${dayLabel} at ${humanTime(plan.start_time)}, starting ${humanDate(dates[0]!, ctx.timezone)}.`,
      facts,
      affects: [
        { kind: 'team', id: ctx.team_id, label: ctx.team_name },
        ...invitedIds.map((id, i) => ({
          kind: 'player' as const,
          id,
          label: invitedNames[i] ?? 'Player',
        })),
      ],
      notifications,
      missing,
      idempotency_key: practiceIdempotencyKey(ctx, plan),
    },
  };
}

/**
 * A key derived from the plan itself, not from a random id.
 *
 * The point is that the same practice series, proposed twice, produces the same
 * key — so a coach who confirms, loses connectivity, and confirms again gets one
 * series. A random UUID would make each attempt look like a new intent, which is
 * precisely the failure this is meant to prevent.
 */
export function practiceIdempotencyKey(ctx: CoachChatContext, plan: RecurringPracticePlan): string {
  const parts = [
    'practice',
    ctx.team_id,
    plan.title.toLowerCase().replace(/\s+/g, '-'),
    plan.start_date,
    plan.start_time,
    plan.weekdays.join(''),
    String(plan.occurrence_count),
  ];
  return parts.join(':').slice(0, 128);
}

/**
 * Execute an approved plan through the existing server action.
 *
 * `createRecurringEvent` owns authorization, the team resolution, RRULE
 * materialisation, attendance/RSVP row creation and the three notification
 * channels. It is imported and called — not reimplemented — so the agent path
 * and the calendar UI path cannot diverge.
 */
export async function executeRecurringPractice(
  ctx: CoachChatContext,
  plan: RecurringPracticePlan,
): Promise<ActionReceipt> {
  const at = new Date().toISOString();
  const { createRecurringEvent } = await import('@/app/golf/actions/recurring-events');

  const recurrenceRule = serializeRecurrenceRule({
    frequency: 'weekly',
    weekdays: plan.weekdays,
    count: plan.occurrence_count,
  });

  // `createRecurringEvent` builds timestamps from a numeric UTC offset in the
  // Date.getTimezoneOffset() convention (positive = behind UTC), so the team's
  // IANA zone is converted to the offset that applies ON THE START DATE. Using
  // today's offset would put a September practice an hour out when the series
  // crosses a DST boundary.
  const timezoneOffset = offsetMinutesForZone(plan.timezone, plan.start_date, plan.start_time);

  const result = await createRecurringEvent({
    title: plan.title,
    description: plan.description ?? undefined,
    eventType: 'practice',
    startDate: plan.start_date,
    startTime: plan.start_time,
    endTime: plan.end_time ?? undefined,
    location: plan.location ?? undefined,
    recurrenceRule,
    requiresRsvp: plan.requires_rsvp,
    rsvpDeadline: plan.rsvp_deadline ?? undefined,
    teamId: ctx.team_id,
    timezoneOffset,
    attendeeIds: plan.invited_player_ids,
  });

  if (!result.success) {
    return {
      status: 'failed',
      action: 'Create a recurring practice',
      summary: 'The practice series was not created.',
      created: [],
      notifications: [],
      partial_failures: [],
      error: result.error ?? 'The calendar rejected the series.',
      retryable: true,
      at,
    };
  }

  const invited = plan.invited_player_ids.length;
  return {
    status: 'completed',
    action: 'Create a recurring practice',
    summary: `${plan.occurrence_count} practices created, every ${plan.weekdays
      .map((d) => WEEKDAY_NAMES[d])
      .join(' and ')} at ${humanTime(plan.start_time)}.`,
    created: [
      {
        kind: 'practice',
        count: plan.occurrence_count,
        href: '/golf/dashboard/calendar',
        label: plan.title,
      },
      ...(plan.requires_rsvp
        ? [{ kind: 'RSVP request', count: invited, href: '/golf/dashboard/calendar' }]
        : []),
    ],
    notifications: [
      { channel: 'In-app', recipients: invited, status: 'sent' as const },
      // Email and push are dispatched in an `after()` callback inside the
      // server action, so at this point they are handed off, not confirmed.
      // Reporting them as 'sent' would be a claim we cannot support.
      { channel: 'Email', recipients: invited, status: 'queued' as const },
      { channel: 'Push', recipients: invited, status: 'queued' as const },
    ],
    partial_failures: [],
    retryable: false,
    at,
  };
}

/**
 * UTC offset in minutes for an IANA zone at a specific local date/time, in the
 * `Date.getTimezoneOffset()` convention (positive = behind UTC).
 *
 * Computed for the series' own start moment rather than "now" so a series that
 * begins after a DST transition is not shifted by an hour.
 */
export function offsetMinutesForZone(timezone: string, isoDate: string, hhmm: string): number {
  try {
    const probe = new Date(`${isoDate}T${hhmm.padStart(5, '0')}:00Z`);
    const parts = new Intl.DateTimeFormat('en-US', {
      timeZone: timezone,
      hour12: false,
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
    }).formatToParts(probe);
    const get = (t: string) => Number(parts.find((p) => p.type === t)?.value ?? '0');
    const asUtc = Date.UTC(
      get('year'),
      get('month') - 1,
      get('day'),
      get('hour') % 24,
      get('minute'),
      get('second'),
    );
    return Math.round((probe.getTime() - asUtc) / 60000);
  } catch {
    // An unknown zone must not silently become UTC and move every practice.
    return new Date().getTimezoneOffset();
  }
}
