// AUTO-GENERATED by scripts/build-course-image-assets.py — do not hand-edit.
// Free-for-commercial course imagery (CC0 / public domain / CC BY / CC BY-SA).
// See public/courses/CREDITS.md for full attribution.
import { normalizeName } from '@/lib/golf/course-library';

/** Cinematic default hero set — every course gets one, chosen deterministically
 *  by name so the same course always shows the same scene. */
export const DEFAULT_COURSE_IMAGES: readonly string[] = [
  '/courses/defaults/sunset-moon.webp',
  '/courses/defaults/red-flag-green.webp',
  '/courses/defaults/dramatic-sky.webp',
  '/courses/defaults/sun-flare-fairway.webp',
  '/courses/defaults/aerial.webp',
  '/courses/defaults/bunker-palms.webp',
  '/courses/defaults/green-pond.webp',
  '/courses/defaults/links-bunker.webp',
] as const;

/** normalized_name -> bundled real-course photo (only where a genuinely good
 *  free photo of THAT course exists). Keyed by golf_normalize_name(name). */
export const REAL_COURSE_IMAGES: Readonly<Record<string, string>> = {
  'bethpage black': '/courses/real/bethpage-black.webp',
  'harbour town golf links': '/courses/real/harbour-town.webp',
  'kiawah island - ocean course': '/courses/real/kiawah-ocean.webp',
  'pebble beach golf club': '/courses/real/pebble-beach.webp',
  'pebble beach golf links': '/courses/real/pebble-beach.webp',
  'reynolds lake oconee - great waters': '/courses/real/reynolds-great-waters.webp',
  'tpc sawgrass': '/courses/real/tpc-sawgrass.webp',
  'tpc sawgrass - stadium': '/courses/real/tpc-sawgrass.webp',
  'whistling straits': '/courses/real/whistling-straits.webp',
};

/** Stable string hash (djb2-ish) — matches the old CourseImage hash so a course
 *  keeps its scene across the gradient→photo switch. */
function hashName(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return Math.abs(h);
}

/** Deterministic cinematic default for a course name. Always returns a path. */
export function resolveDefaultCourseImage(name: string): string {
  const i = hashName(name || 'course') % DEFAULT_COURSE_IMAGES.length;
  return DEFAULT_COURSE_IMAGES[i]!;
}

/** Bundled real-course photo for a course, or null if none exists. Matches on
 *  the stored normalized_name first, then falls back to normalizing the name. */
export function resolveRealCourseImage(
  name: string,
  normalizedName?: string | null,
): string | null {
  const key = (normalizedName && normalizedName.trim()) || normalizeName(name);
  return REAL_COURSE_IMAGES[key] ?? null;
}

export interface CourseImageCredit {
  file: string;
  title: string;
  license: string;
  attribution: string;
}
export const COURSE_IMAGE_CREDITS: readonly CourseImageCredit[] = [
  {
    file: '/courses/defaults/sunset-moon.webp',
    title: 'Free beautiful golf field photo',
    license: 'cc0 1.0',
    attribution: '"Free beautiful golf field photo" is marked with CC0 1.0. To view the terms, visit https://creativecommons.org/publicdomain/zero/1.0/.',
  },
  {
    file: '/courses/defaults/red-flag-green.webp',
    title: 'DZ6 2470 Perfect day on the green - calm skies crisp fairways and a flag waiting for the next putt',
    license: 'by-sa 4.0',
    attribution: '"DZ6 2470 Perfect day on the green - calm skies crisp fairways and a flag waiting for the next putt" by PattayaPatrol is licensed under CC BY-SA 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-sa/4.0/.',
  },
  {
    file: '/courses/defaults/dramatic-sky.webp',
    title: 'colorful evening sky over a golf course',
    license: 'cc0 1.0',
    attribution: '"colorful evening sky over a golf course" by Jacob Martella is marked with CC0 1.0. To view the terms, visit https://creativecommons.org/publicdomain/zero/1.0/.',
  },
  {
    file: '/courses/defaults/sun-flare-fairway.webp',
    title: 'DZ6 2466 Sunny morning stroll down the fairway - calm greens clear skies and a perfect day on the course',
    license: 'by-sa 4.0',
    attribution: '"DZ6 2466 Sunny morning stroll down the fairway - calm greens clear skies and a perfect day on the course" by PattayaPatrol is licensed under CC BY-SA 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-sa/4.0/.',
  },
  {
    file: '/courses/defaults/aerial.webp',
    title: 'Sunset Golf Course Aerial - Middletown (51146830409)',
    license: 'by-sa 2.0',
    attribution: '"Sunset Golf Course Aerial - Middletown (51146830409)" by formulanone is licensed under CC BY-SA 2.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-sa/2.0/.',
  },
  {
    file: '/courses/defaults/bunker-palms.webp',
    title: 'DZ6 2423 A sunlit golf course with a neatly raked bunker in the foreground and palm trees lining the fairway',
    license: 'by-sa 4.0',
    attribution: '"DZ6 2423 A sunlit golf course with a neatly raked bunker in the foreground and palm trees lining the fairway" by PattayaPatrol is licensed under CC BY-SA 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-sa/4.0/.',
  },
  {
    file: '/courses/defaults/green-pond.webp',
    title: 'DZ6 2525 Sunny day on the green a yellow flag flutters as golfers line up their next putt',
    license: 'by-sa 4.0',
    attribution: '"DZ6 2525 Sunny day on the green a yellow flag flutters as golfers line up their next putt" by PattayaPatrol is licensed under CC BY-SA 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-sa/4.0/.',
  },
  {
    file: '/courses/defaults/links-bunker.webp',
    title: 'DZ6 2459 Sunlit golf course fairway with a sand bunker in the foreground and trees under a clear blue sky',
    license: 'by-sa 4.0',
    attribution: '"DZ6 2459 Sunlit golf course fairway with a sand bunker in the foreground and trees under a clear blue sky" by PattayaPatrol is licensed under CC BY-SA 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-sa/4.0/.',
  },
  {
    file: '/courses/real/bethpage-black.webp',
    title: 'File:Bethpage Golf Course.jpg',
    license: 'CC0',
    attribution: 'File:Bethpage Golf Course.jpg by Bonnachoven',
  },
  {
    file: '/courses/real/harbour-town.webp',
    title: 'File:Harbour Town Golf Links, Hilton Head - 5111730582.jpg',
    license: 'CC BY 2.0',
    attribution: 'File:Harbour Town Golf Links, Hilton Head - 5111730582.jpg by danperry.com',
  },
  {
    file: '/courses/real/kiawah-ocean.webp',
    title: 'File:Ocean course 18th green.jpg',
    license: 'CC BY-SA 4.0',
    attribution: 'File:Ocean course 18th green.jpg by N75746',
  },
  {
    file: '/courses/real/pebble-beach.webp',
    title: 'File:Pebble Beach Golf Links 02.jpg',
    license: 'CC BY 2.5',
    attribution: 'File:Pebble Beach Golf Links 02.jpg by Tewy',
  },
  {
    file: '/courses/real/reynolds-great-waters.webp',
    title: 'File:Great Waters at Reynolds Lake Oconee - Oct 2019.jpg',
    license: 'CC BY-SA 4.0',
    attribution: 'File:Great Waters at Reynolds Lake Oconee - Oct 2019.jpg by Jim Mandeville',
  },
  {
    file: '/courses/real/tpc-sawgrass.webp',
    title: 'File:TPC at Sawgrass (3424744578).jpg',
    license: 'CC BY-SA 2.0',
    attribution: 'File:TPC at Sawgrass (3424744578).jpg by Philip Larson from McLean, VA, US',
  },
  {
    file: '/courses/real/whistling-straits.webp',
    title: 'File:WhistlingStraits11Fairway.JPG',
    license: 'Public domain',
    attribution: 'File:WhistlingStraits11Fairway.JPG by User:KevinTR',
  },
];
