// =============================================================================
// src/components/baseball/source-trust/trust-presentation.ts
//
// Pure presentation resolver for the Source Trust System. Maps a `SourceTrust`
// descriptor onto a cream/green tone, an icon key, and the human trust label.
// Shared by SourceTrustBadge + SourceDrawer so the two NEVER drift.
//
// HONESTY ORDER OF PRECEDENCE (binding):
//   1. conflict        -> error red,    "Conflict" — never reads as trusted.
//   2. logged_intent   -> neutral warm,  "Planned" — not yet observed.
//   3. ai_derived      -> neutral warm,  "AI-derived" — interpretation, cite
//                         (the `sparkles` icon — NOT a hue — differentiates it).
//   4. unreviewed /
//      unknown kind     -> neutral warm,  "Unreviewed" — present, not verified.
//   5. verified active  -> primary green, "Verified".
//   6. otherwise        -> neutral warm by kind, honest provenance label.
//
// PALETTE (binding owner decision): cream/green GolfHelm system only — primary
// green is the SINGLE positive accent, red = error (conflict: two sources
// disagree), amber = caution (low-confidence / inferred), warm = neutral. These
// four tones mirror the data-quality scale already used by StatVisualFrame +
// DataQualityVisuals (medium=warm, caveat=amber, conflict/regression=red). No
// blue/violet/teal categorical hues; provenance tiers differ by ICON, never hue
// (matches StatVisualFrame + Fairway, which carry zero blue/violet tokens).
//
// NOTE: conflict deliberately maps to RED, not amber — a conflict is an error
// (do not rely on this value), distinct from amber low-confidence which is a
// soft caution. Collapsing both to amber would hide that severity difference.
// Pure module — safe to import from server read models or client components.
// =============================================================================

import type { BadgeTone } from '@/components/ui/badge';
import type {
  SourceTrust,
  TrustLevel,
  SourceKind,
} from './source-trust-types';

export type TrustIconKey =
  | 'shield-check' // verified / official
  | 'shield' // staff/player entered, reviewed-but-not-verified
  | 'database' // device export / integration
  | 'file' // imported / attached report
  | 'sparkles' // ai-derived
  | 'shield-alert' // conflict
  | 'clock' // logged intent (planned)
  | 'info'; // unreviewed / unknown

export interface TrustPresentation {
  tone: BadgeTone;
  icon: TrustIconKey;
  /** Human trust label, e.g. "Verified", "AI-derived", "Planned". */
  trustLabel: string;
  /** Honest one-line caption for the drawer header. */
  caption: string;
}

const KIND_DEFAULT_TRUST: Record<SourceKind, TrustLevel> = {
  manual: 'staff_entered',
  csv_import: 'imported',
  integration: 'device_export',
  ai: 'ai_derived',
  system: 'imported',
  unknown: 'unreviewed',
};

/** Resolve the effective trust tier from the descriptor + low-level flags. */
export function resolveTrustLevel(trust: SourceTrust): TrustLevel {
  if (trust.conflict) return 'conflict';
  if (trust.trustLevel) return trust.trustLevel;
  if (trust.kind === 'unknown') return 'unreviewed';
  return KIND_DEFAULT_TRUST[trust.kind];
}

const TRUST_LABELS: Record<TrustLevel, string> = {
  official: 'Official',
  device_export: 'Device export',
  staff_entered: 'Staff entered',
  player_entered: 'Player entered',
  imported: 'Imported',
  attached_report: 'Attached report',
  ai_derived: 'AI-derived',
  unreviewed: 'Unreviewed',
  conflict: 'Conflict',
};

/** Map a trust descriptor onto tone + icon + label, honesty-first. */
export function getTrustPresentation(trust: SourceTrust): TrustPresentation {
  // 1. Conflict always wins — it must read as "do not trust yet". Red (error),
  //    NOT amber: a conflict is a real disagreement to resolve, a harder signal
  //    than an amber low-confidence caution (matches the data-quality scale).
  if (trust.conflict) {
    return {
      tone: 'red',
      icon: 'shield-alert',
      trustLabel: 'Conflict',
      caption: 'Two sources disagree on this value. Resolve before relying on it.',
    };
  }

  // 2. Logged intent — planned/assigned, NOT observed.
  if (trust.captureMode === 'logged_intent') {
    return {
      tone: 'warm',
      icon: 'clock',
      trustLabel: 'Planned',
      caption: 'Planned or assigned — not yet observed or recorded.',
    };
  }

  const level = resolveTrustLevel(trust);

  // 3. AI-derived — interpretation, must cite sources.
  if (level === 'ai_derived' || trust.kind === 'ai') {
    return {
      tone: 'warm',
      icon: 'sparkles',
      trustLabel: 'AI-derived',
      caption: 'Generated by CoachHelm from cited sources. Review before acting.',
    };
  }

  // 4. Unreviewed / unknown — present, but not verified.
  if (level === 'unreviewed' || trust.kind === 'unknown') {
    return {
      tone: 'warm',
      icon: 'info',
      trustLabel: 'Unreviewed',
      caption: 'Recorded but not yet reviewed by staff.',
    };
  }

  // 5. Verified active capture — the high-trust state.
  if (trust.verified) {
    return {
      tone: 'primary',
      icon: level === 'official' ? 'shield-check' : 'shield-check',
      trustLabel: level === 'official' ? 'Official · Verified' : 'Verified',
      caption:
        level === 'official'
          ? 'From an official feed and verified by staff.'
          : 'Reviewed and verified by staff.',
    };
  }

  // 6. By kind — honest provenance without claiming verification.
  switch (level) {
    case 'official':
      return {
        tone: 'warm',
        icon: 'shield-check',
        trustLabel: 'Official',
        caption: 'From an official feed. Not yet staff-verified.',
      };
    case 'device_export':
      return {
        tone: 'warm',
        icon: 'database',
        trustLabel: 'Device export',
        caption: 'Exported from a measurement device or integration.',
      };
    case 'attached_report':
      return {
        tone: 'warm',
        icon: 'file',
        trustLabel: 'Attached report',
        caption: 'From an attached document or report.',
      };
    case 'imported':
      return {
        tone: 'warm',
        icon: 'file',
        trustLabel: 'Imported',
        caption: 'Came through the import pipeline. Not yet staff-verified.',
      };
    case 'player_entered':
      return {
        tone: 'warm',
        icon: 'shield',
        trustLabel: 'Player entered',
        caption: 'Entered by the player. Not yet staff-verified.',
      };
    case 'staff_entered':
    default:
      return {
        tone: 'warm',
        icon: 'shield',
        trustLabel: TRUST_LABELS[level] ?? 'Staff entered',
        caption: 'Entered by staff. Not yet marked verified.',
      };
  }
}

/** Confidence figure presentation. Honest: null -> "—", low -> de-emphasized. */
export function formatConfidence(pct: number | null): {
  text: string;
  /** True when the value is low enough that the UI should soften it. */
  low: boolean;
  /** True when there is no confidence figure at all. */
  missing: boolean;
} {
  if (pct === null) return { text: '—', low: false, missing: true };
  return { text: `${pct}%`, low: pct < 60, missing: false };
}
