#!/usr/bin/env tsx
/**
 * gen-feature-map.ts — render docs/generated/HELM_FEATURE_MAP.md.
 *
 * A PROJECTION, not a source of truth. Every cell is read from an authority and
 * every description is a link rather than a summary, because a hand-maintained
 * feature map is exactly the second copy that ADR-2026-08-30 forbids: it looks
 * as confident as the registry it drifts from.
 *
 * Inputs, all of them authorities in their own right:
 *
 *   memory/registry.yml                 semantic identity, docs, code, crosswalk
 *   src/lib/admin/feature-registry.ts   runtime FeatureKey vocabulary
 *   memory/incidents/<feature_id>/      confirmed defects
 *   memory/operations/release-queue.yml in-flight repair units
 *   memory/ledgers/{changes,tests}/     semantic history
 *
 * DETERMINISM IS A REQUIREMENT, not a nicety. `--check` re-renders and diffs, so
 * anything order-dependent or time-dependent would flap in CI and train people
 * to rerun until green. Everything below iterates in declared or sorted order
 * and nothing reads the clock.
 *
 * Usage:
 *   npx tsx scripts/knowledge/gen-feature-map.ts            # write
 *   npx tsx scripts/knowledge/gen-feature-map.ts --check    # verify, no write
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as yaml from 'js-yaml';

import { FEATURE_REGISTRY } from '../../src/lib/admin/feature-registry';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');

/**
 * Only run when invoked as a command. Tests import the pure function above, and
 * a module that does work on import would run the real check inside the test
 * process — quietly setting process.exitCode and making a suite fail for a
 * reason that has nothing to do with the suite.
 */
const isEntrypoint = process.argv[1] !== undefined
  && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
const OUT = resolve(ROOT, 'docs/generated/HELM_FEATURE_MAP.md');

interface Feature {
  name?: string;
  status?: string;
  owner?: string;
  criticality?: string;
  docs?: { feature?: string };
  code?: Record<string, string[] | undefined>;
  observability?: { feature_keys?: string[]; covered_by?: string; reason?: string };
}

interface RepairUnit {
  id?: string;
  feature_id?: string;
  status?: string;
  incident_id?: string | null;
}

function loadRegistry() {
  return yaml.load(readFileSync(resolve(ROOT, 'memory/registry.yml'), 'utf8')) as {
    features?: Record<string, Feature>;
    observability_keys_unowned?: Record<string, { classification?: string; reason?: string }>;
  };
}

function loadQueue(): RepairUnit[] {
  const p = resolve(ROOT, 'memory/operations/release-queue.yml');
  if (!existsSync(p)) return [];
  const q = yaml.load(readFileSync(p, 'utf8')) as { items?: RepairUnit[] };
  return q?.items ?? [];
}

function incidentsFor(id: string): string[] {
  const dir = resolve(ROOT, 'memory/incidents', id);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.startsWith('INC-') && f.endsWith('.md'))
    .sort();
}

/** The code globs a feature declares, flattened and deduplicated, in file order. */
function surfaces(f: Feature): string[] {
  const out: string[] = [];
  for (const v of Object.values(f.code ?? {})) if (Array.isArray(v)) out.push(...v);
  return [...new Set(out)];
}

function render(): string {
  const reg = loadRegistry();
  const features = reg.features ?? {};
  const unowned = reg.observability_keys_unowned ?? {};
  const queue = loadQueue();
  const runtimeByKey = new Map(FEATURE_REGISTRY.map((f) => [f.key as string, f]));

  const L: string[] = [];
  L.push('# Helm feature map');
  L.push('');
  // MD013 is disabled for the whole file, in the GENERATOR rather than by hand.
  // A row lists every code glob and every FeatureKey a feature owns; wrapping
  // those would make the map less readable to buy a lint number, and a fix
  // applied to the output would be undone by the next regeneration.
  L.push('<!-- markdownlint-disable MD013 -->');
  L.push('<!-- GENERATED by scripts/knowledge/gen-feature-map.ts — do not edit. -->');
  L.push('<!-- Regenerate: npm run knowledge:feature-map  ·  Verify: npm run knowledge:check -->');
  L.push('');
  L.push('**Navigation, not truth.** Every column is read from an authority and every');
  L.push('description is a link rather than a summary. If you want to know how a feature');
  L.push('behaves, open its doc; if you want to know whether it is healthy, open Mission');
  L.push('Control. Nothing is restated here, on purpose — a second copy of a description');
  L.push('is a second thing to keep true.');
  L.push('');
  L.push('| Authority | What it owns |');
  L.push('| --- | --- |');
  L.push('| `memory/registry.yml` | which files and runtime keys belong to a feature |');
  L.push('| the mapped feature doc | how that feature behaves now |');
  L.push('| `src/lib/admin/feature-registry.ts` | the runtime `FeatureKey` vocabulary |');
  L.push('| `memory/incidents/**` | confirmed defects |');
  L.push('| `memory/operations/release-queue.yml` | repair units in flight |');
  L.push('');
  L.push('---');
  L.push('');

  for (const id of Object.keys(features)) {
    const f = features[id];
    const obs = f.observability ?? {};
    const keys = obs.feature_keys ?? [];
    const incs = incidentsFor(id);
    const repairs = queue.filter((r) => r.feature_id === id);

    L.push(`## \`${id}\``);
    L.push('');
    L.push(`**${f.name ?? id}** · ${f.status ?? 'unknown'} · criticality ${f.criticality ?? 'unknown'} · owner ${f.owner ?? 'unknown'}`);
    L.push('');
    L.push(`- **Behaviour:** \`${f.docs?.feature ?? '(none declared)'}\``);

    const s = surfaces(f);
    if (s.length) {
      const shown = s.slice(0, 6).map((g) => `\`${g}\``).join(', ');
      L.push(`- **Code:** ${shown}${s.length > 6 ? ` … and ${s.length - 6} more in the registry` : ''}`);
    } else {
      L.push('- **Code:** none declared');
    }

    if (keys.length) {
      const rows = keys.map((k) => {
        const r = runtimeByKey.get(k) as { app?: string; tier?: string; primaryTable?: string } | undefined;
        return `\`${k}\` (${r?.app ?? '?'}, ${r?.tier ?? '?'})`;
      });
      L.push(`- **Telemetry:** ${rows.join(', ')}`);
    } else {
      const via = obs.covered_by ? ` — covered by \`${obs.covered_by}\`` : '';
      L.push(`- **Telemetry:** none${via}. ${obs.reason ?? ''}`.trimEnd());
    }

    L.push(
      incs.length
        ? `- **Incidents:** ${incs.map((i) => `\`memory/incidents/${id}/${i}\``).join(', ')}`
        : '- **Incidents:** none recorded',
    );
    L.push(
      repairs.length
        ? `- **Repair units:** ${repairs.map((r) => `\`${r.id}\` (${r.status})`).join(', ')}`
        : '- **Repair units:** none in the queue',
    );

    const changes = `memory/ledgers/changes/${id}.md`;
    const tests = `memory/ledgers/tests/${id}.md`;
    const hist: string[] = [];
    if (existsSync(resolve(ROOT, changes))) hist.push(`\`${changes}\``);
    if (existsSync(resolve(ROOT, tests))) hist.push(`\`${tests}\``);
    L.push(`- **History:** ${hist.length ? hist.join(', ') : 'no ledger yet'}`);
    L.push('');
  }

  L.push('---');
  L.push('');
  L.push('## Runtime keys with no semantic owner');
  L.push('');
  L.push('A key that nobody owns is *said* to be unowned. Leaving it off every list');
  L.push('would be indistinguishable from an oversight, which is the whole failure this');
  L.push('reconciliation removes.');
  L.push('');
  for (const k of Object.keys(unowned)) {
    const e = unowned[k];
    L.push(`- \`${k}\` — **${e.classification}**. ${e.reason ?? ''}`.trimEnd());
  }
  // Collapse any run of blank lines the section builders left behind, and end
  // on exactly one newline. Emitting well-formed markdown is the generator's
  // job — a hand-fix here would be undone by the next regeneration.
  const body = L.join('\n').replace(/\n{3,}/g, '\n\n').replace(/\s+$/, '');
  return `${body}\n`;
}

function main(): void {
  const check = process.argv.includes('--check');
  const next = render();
  // Read once and treat "not there" as "empty", rather than asking existsSync
  // and then reading. The two-call form is a genuine TOCTOU — CodeQL flags it
  // as js/file-system-race — and the single call is also simpler.
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    /* first run, or the file was removed between generations */
  }

  if (!check) {
    writeFileSync(OUT, next);
    console.log(`Wrote docs/generated/HELM_FEATURE_MAP.md (${next.split('\n').length} lines).`);
    return;
  }

  if (current === next) {
    console.log('✅ docs/generated/HELM_FEATURE_MAP.md matches its sources.');
    return;
  }

  const a = current.split('\n');
  const b = next.split('\n');
  const i = a.findIndex((l, n) => l !== b[n]);
  console.error('\n❌ docs/generated/HELM_FEATURE_MAP.md is out of date.\n');
  console.error(`   first difference at line ${i + 1}`);
  console.error(`     file:     ${JSON.stringify(a[i] ?? '(end of file)')}`);
  console.error(`     expected: ${JSON.stringify(b[i] ?? '(end of file)')}`);
  console.error('\n   Run: npm run knowledge:feature-map\n');
  process.exitCode = 1;
}

if (isEntrypoint) main();
