// AUTOGENERATED — DO NOT EDIT BY HAND.
//
// Generated by `npm run flags:generate` (scripts/flags/generate-flags.mjs)
// from `config/feature-flags.yml`. A stamp saying so is not evidence this
// file is current — `npm run flags:check` re-parses the YAML independently
// and fails if this file has drifted (shipping.md §1: "verify the
// generator, not the stamp").
//
// Compiled to a typed constant on purpose: reading the flag registry at
// request time never touches the filesystem or parses YAML.

import type { FlagDefinition } from './types';

export const FLAG_REGISTRY: readonly FlagDefinition[] = [
  {
    feature_id: "coachhelm_v2_availability",
    owner: "golf/coachhelm",
    purpose: "Global product-availability switch for the CoachHelm V2 AI layer. Off disables the whole surface for every coach and player account; the underlying check is a fail-open string comparison (any value except the literal string \"false\" leaves it on).",
    type: "release",
    status: "active",
    created_at: "2026-09-03",
    expires_at: null,
    default: true,
    environment: {
      production: true,
      preview: true,
      development: true,
    },
    kill_switch_behavior: null,
    cleanup_plan: "No planned removal — this has been the live product-availability switch for CoachHelm V2 since its rollout; this registry entry documents it without wiring the call site, which lives outside this PR's scope. A future session may wire src/lib/coachhelm/v2/gate.ts through isFlagEnabled('coachhelm_v2_availability') as a small, independent follow-up.",
  },
  {
    feature_id: "flight_recorder",
    owner: "platform (Bridge)",
    purpose: "Arms per-request golf round mutation tracing (client to server action to RPC to in-transaction checkpoints) so /admin/traces has data to show. An operability lever only — disabling it stops the mutation from being observed, never stops the mutation from running.",
    type: "operations_kill_switch",
    status: "active",
    created_at: "2026-09-03",
    expires_at: null,
    default: true,
    environment: {
      production: false,
      preview: true,
      development: true,
    },
    kill_switch_behavior: "Off: no helm_debug_start_trace / helm_debug_record_trace_step / helm_debug_finalize_trace RPCs are called from the golf round action path. The round mutation itself is unaffected — this switch only controls whether it is observed. Changed by setting HELM_FLIGHT_RECORDER_ENABLED at the environment level (deploy-time, not a runtime toggle); auditable via the Vercel environment-variable change log.",
    cleanup_plan: "No planned removal — permanent ops tooling. This registry entry documents the existing toggle; it does not wire the call sites, which sit outside this PR's file-ownership boundary. Wiring is left to the Sentry session that owns those two files.",
  },
  {
    feature_id: "meridian_live_sync_v1",
    owner: "golf/course-geometry",
    purpose: "Shared release flag for the One-Tap server outbox on any layout whose approvals.json entry names it as `syncFeatureFlag`; off, an eligible Live round plays device-only. Requires that layout's own outbox migration be applied first — turning this on for an environment whose migration is unapplied will fail every sync write.",
    type: "release",
    status: "active",
    created_at: "2026-09-22",
    expires_at: null,
    default: false,
    environment: {
      production: false,
      preview: true,
      development: true,
    },
    kill_switch_behavior: null,
    cleanup_plan: "No planned removal while any registry layout names it. Reassess if every layout migrates to its own dedicated flag.",
  },
  {
    feature_id: "meridian_live_v1",
    owner: "golf/course-geometry",
    purpose: "Shared release flag for Meridian Live course drawing / One-Tap on any layout whose approvals.json entry names it as `geometryFeatureFlag`. Off returns an eligible round to standard GolfHelm shot tracking; on alone draws nothing without that layout's own approved package hash.",
    type: "release",
    status: "active",
    created_at: "2026-09-22",
    expires_at: null,
    default: false,
    environment: {
      production: false,
      preview: true,
      development: true,
    },
    kill_switch_behavior: null,
    cleanup_plan: "No planned removal while any registry layout names it — this is shared, ongoing product infrastructure, not a single-course pilot flag. Reassess if every layout migrates to its own dedicated flag.",
  },
  {
    feature_id: "peek_n_peak_one_tap_sync_v1",
    owner: "golf/course-geometry",
    purpose: "Enables the One-Tap server outbox for Peek'n Peak Upper (mirroring resolved anchors to `golf_shot_anchors` & co.) once `20260916_peek_n_peak_one_tap.sql` is applied; off, an eligible Live round still plays fully on-device and its score still reaches the standard ledger. Chooses a mirroring destination only — never an eligibility gate.",
    type: "release",
    status: "active",
    created_at: "2026-09-22",
    expires_at: null,
    default: false,
    environment: {
      production: false,
      preview: false,
      development: false,
    },
    kill_switch_behavior: null,
    cleanup_plan: "Removed alongside peek_n_peak_one_tap_v1 when the Upper pilot graduates or is withdrawn; flip to true per environment only after that environment's migration is confirmed applied (information_schema, not schema_migrations — see .claude/rules/database.md \"Applied ≠ recorded\").",
  },
  {
    feature_id: "peek_n_peak_one_tap_v1",
    owner: "golf/course-geometry",
    purpose: "Enables the Peek'n Peak Upper One-Tap live round (MARK BALL on the Meridian 3D course) for eligible rounds; off returns those rounds to standard GolfHelm shot tracking. It only selects which tracker screen an eligible Upper round shows; no other course is affected.",
    type: "release",
    status: "active",
    created_at: "2026-09-16",
    expires_at: null,
    default: false,
    environment: {
      production: false,
      preview: true,
      development: true,
    },
    kill_switch_behavior: null,
    cleanup_plan: "Removed when the Upper pilot either graduates to a general Meridian Live launch (a separate architectural project) or is withdrawn; either way the flag row is deleted and the eligibility gate keeps the course/site/hash/capability checks.",
  },
  {
    feature_id: "verification_ensemble",
    owner: "platform (Bridge)",
    purpose: "Runs a multi-pass adversarial/security/product review chain over an already-produced root-cause analysis before it reaches the repair queue; default off, no recurring cost.",
    type: "operations_kill_switch",
    status: "active",
    created_at: "2026-09-03",
    expires_at: null,
    default: false,
    environment: {
      production: false,
      preview: false,
      development: false,
    },
    kill_switch_behavior: "Off (the default everywhere): runVerificationEnsemble returns status: 'disabled' immediately, before resolving a model provider or calling generateObject — zero additional model calls beyond today's single Diagnose call. On: adds up to four more model calls (ADVERSARY, conditional SECURITY, PRODUCT, JUDGE) per invocation, on the same Anthropic account Diagnose already uses. Changed by editing this file's environment block and running npm run flags:generate; auditable via git history on config/feature-flags.yml.",
    cleanup_plan: "No planned removal — permanent ops lever gating a genuinely optional verification pass, not a migration bridge.",
  },
] as const;
