// AUTOGENERATED — DO NOT EDIT BY HAND.
//
// Generated by `npm run flags:generate` (scripts/flags/generate-flags.mjs)
// from `config/feature-flags.yml`. A stamp saying so is not evidence this
// file is current — `npm run flags:check` re-parses the YAML independently
// and fails if this file has drifted (shipping.md §1: "verify the
// generator, not the stamp").
//
// Compiled to a typed constant on purpose: reading the flag registry at
// request time never touches the filesystem or parses YAML.

import type { FlagDefinition } from './types';

export const FLAG_REGISTRY: readonly FlagDefinition[] = [
  {
    feature_id: "coachhelm_v2_availability",
    owner: "golf/coachhelm",
    purpose: "Global product-availability switch for the CoachHelm V2 AI layer. Off disables the whole surface for every coach and player account; the underlying check is a fail-open string comparison (any value except the literal string \"false\" leaves it on).",
    type: "release",
    status: "active",
    created_at: "2026-09-03",
    expires_at: null,
    default: true,
    environment: {
      production: true,
      preview: true,
      development: true,
    },
    kill_switch_behavior: null,
    cleanup_plan: "No planned removal — this has been the live product-availability switch for CoachHelm V2 since its rollout; this registry entry documents it without wiring the call site, which lives outside this PR's scope. A future session may wire src/lib/coachhelm/v2/gate.ts through isFlagEnabled('coachhelm_v2_availability') as a small, independent follow-up.",
  },
  {
    feature_id: "flight_recorder",
    owner: "platform (Bridge)",
    purpose: "Arms per-request golf round mutation tracing (client to server action to RPC to in-transaction checkpoints) so /admin/traces has data to show. An operability lever only — disabling it stops the mutation from being observed, never stops the mutation from running.",
    type: "operations_kill_switch",
    status: "active",
    created_at: "2026-09-03",
    expires_at: null,
    default: true,
    environment: {
      production: false,
      preview: true,
      development: true,
    },
    kill_switch_behavior: "Off: no helm_debug_start_trace / helm_debug_record_trace_step / helm_debug_finalize_trace RPCs are called from the golf round action path. The round mutation itself is unaffected — this switch only controls whether it is observed. Changed by setting HELM_FLIGHT_RECORDER_ENABLED at the environment level (deploy-time, not a runtime toggle); auditable via the Vercel environment-variable change log.",
    cleanup_plan: "No planned removal — permanent ops tooling. This registry entry documents the existing toggle; it does not wire the call sites, which sit outside this PR's file-ownership boundary. Wiring is left to the Sentry session that owns those two files.",
  },
] as const;
