/**
 * Sentry as the exception front door — brief §71, §72.
 *
 * Sentry already receives Helm's exceptions. This module decides exactly
 * WHAT rides along with a Supabase failure, and it is built as an
 * ALLOW-LIST rather than as a scrubber.
 *
 * WHY ALLOW-LIST AND NOT SCRUB
 * -----------------------------
 * A scrubber has to recognise every bad thing. An allow-list has to
 * recognise ten good things. The failure modes are not symmetrical: a
 * scrubber that misses a pattern ships the secret, while an allow-list that
 * misses a pattern ships nothing. `buildSentrySupabaseTags` copies the ten
 * keys brief §71 names out of its source and structurally cannot carry an
 * eleventh — raw SQL, a filter value, a request body, a cookie or an
 * Authorization header is not masked, it is simply never copied, and its
 * VALUE is never reported back either (only the key name, so an operator can
 * see something was dropped without the drop itself becoming the leak).
 *
 * AN ALLOW-LISTED KEY WITH AN UNSAFE VALUE IS REFUSED, NOT MASKED
 * ----------------------------------------------------------------
 * A tag is a queryable dimension. Masking a UUID to `[id]` and keeping the
 * tag still creates a series, and the presence of that series is itself
 * information. So a value that looks like a UUID, an email, a JWT or a
 * bearer token is dropped and the refusal recorded.
 *
 * The ONE exception is `helm.trace_id`, and it is the exception brief §6
 * itself carves out: "a trace may reference one deliberately selected
 * internal entity id to diagnose one workflow, but user/team/round UUIDs are
 * never metric dimensions." A trace id IS a correlation id — it exists to be
 * joined on — and Helm's is a UUID. Refusing it would break the correlation
 * the whole front door is for.
 *
 * THREE TRACE IDS, AND THEY ARE NOT THE SAME THING (§72)
 * -------------------------------------------------------
 *   sentryTraceId  Sentry's own trace id, from the active span's
 *                  `spanContext()`. Generated by the Sentry SDK. This is
 *                  what a Sentry trace view is keyed on.
 *   w3cTraceId     The `traceparent` trace-id that crossed the HTTP
 *                  boundary. It may have been created by an upstream
 *                  caller, or by supabase-js's own propagation, and it is
 *                  what a NON-Sentry participant in the same request can
 *                  see. Certifying that it propagates is §14's job.
 *   helmTraceId    Helm's own id, the one `trace_runs`, `error_logs` and
 *                  `admin_events` carry. It survives past the request that
 *                  produced it and is what the Bridge joins on.
 *
 * They frequently coincide — Sentry's SDK will adopt an incoming
 * `traceparent` — and that is exactly why they must be stored separately.
 * Assuming equality works right up until a trace arrives from a runtime
 * where Sentry did not continue the upstream trace, at which point every
 * join built on that assumption silently returns nothing.
 * `buildTraceCorrelation` therefore keeps three named fields, never one
 * `traceId`, and REPORTS whether the first two matched instead of deciding
 * they always do.
 *
 * Pure: no Sentry import, no I/O, no server-only import. The caller passes
 * the returned tags to `Sentry.setTags` / `scope.setTags`.
 */
import { sanitizeSupabaseFreeText, type SupabaseErrorEnvelope } from './envelope';

// ---------------------------------------------------------------------------
// The allow-list
// ---------------------------------------------------------------------------

export const SENTRY_SUPABASE_TAG_KEYS = [
  'supabase.service',
  'supabase.operation',
  'supabase.rpc',
  'supabase.relation',
  'supabase.code',
  'postgres.sqlstate',
  'helm.feature',
  'helm.action',
  'helm.trace_id',
  'release',
] as const;

export type SentrySupabaseTagKey = (typeof SENTRY_SUPABASE_TAG_KEYS)[number];

const ALLOWED = new Set<string>(SENTRY_SUPABASE_TAG_KEYS);

/** The one key exempt from the correlation-id refusal — see the header. */
const CORRELATION_ID_KEYS = new Set<string>(['helm.trace_id']);

/** A tag is a dimension, not a payload. Anything longer is refused. */
export const MAX_TAG_VALUE_CHARS = 200;

const UUID_RE = /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i;
const EMAIL_RE = /[^\s@]+@[^\s@]+\.[^\s@]+/;
const JWT_RE = /eyJ[A-Za-z0-9_-]{6,}\.[A-Za-z0-9_-]{6,}\.[A-Za-z0-9_-]{6,}/;
const BEARER_RE = /\bbearer\s+\S{12,}/i;

// ---------------------------------------------------------------------------
// Result
// ---------------------------------------------------------------------------

export interface RefusedTagValue {
  key: SentrySupabaseTagKey;
  /** Why it was refused. Never the value itself. */
  reason: string;
}

export interface SentrySupabasePayload {
  /** Only allow-listed keys with safe, present values. */
  tags: Readonly<Partial<Record<SentrySupabaseTagKey, string>>>;
  correlation: TraceCorrelation;
  /** Source keys that are not on the allow-list. Names only, never values. */
  droppedKeys: readonly string[];
  refusedValues: readonly RefusedTagValue[];
}

// ---------------------------------------------------------------------------
// Trace correlation
// ---------------------------------------------------------------------------

export interface SupabaseTraceIds {
  sentryTraceId: string | null;
  w3cTraceId: string | null;
  helmTraceId: string | null;
}

export interface TraceCorrelation {
  sentryTraceId: string | null;
  w3cTraceId: string | null;
  helmTraceId: string | null;
  /** Observed, not assumed. See the header. */
  sentryMatchesW3c: boolean;
}

/** W3C `trace-id`: 32 lowercase hex characters, and not all zeros (the spec
 *  reserves the all-zero id as invalid). Sentry uses the same shape. */
const W3C_TRACE_ID_RE = /^[0-9a-f]{32}$/;
const ALL_ZERO_TRACE_ID = '0'.repeat(32);

function normalizeW3cStyleTraceId(value: string | null): string | null {
  if (!value) return null;
  const trimmed = value.trim().toLowerCase();
  if (!W3C_TRACE_ID_RE.test(trimmed) || trimmed === ALL_ZERO_TRACE_ID) return null;
  return trimmed;
}

/** Helm's own id is a UUID or another bounded opaque token; it is not
 *  required to be W3C-shaped, so it is only bounded and sanitized. */
function normalizeHelmTraceId(value: string | null): string | null {
  if (!value) return null;
  const trimmed = value.trim();
  if (trimmed.length === 0 || trimmed.length > MAX_TAG_VALUE_CHARS) return null;
  if (EMAIL_RE.test(trimmed) || JWT_RE.test(trimmed)) return null;
  return trimmed;
}

export function buildTraceCorrelation(ids: SupabaseTraceIds): TraceCorrelation {
  const sentryTraceId = normalizeW3cStyleTraceId(ids.sentryTraceId);
  const w3cTraceId = normalizeW3cStyleTraceId(ids.w3cTraceId);
  return {
    sentryTraceId,
    w3cTraceId,
    helmTraceId: normalizeHelmTraceId(ids.helmTraceId),
    sentryMatchesW3c: sentryTraceId !== null && w3cTraceId !== null && sentryTraceId === w3cTraceId,
  };
}

// ---------------------------------------------------------------------------
// Tag builder
// ---------------------------------------------------------------------------

function refuseReason(key: string, value: string): string | null {
  if (value.length > MAX_TAG_VALUE_CHARS) return `value length exceeds ${MAX_TAG_VALUE_CHARS} characters`;
  if (EMAIL_RE.test(value)) return 'value looks like an email address';
  if (JWT_RE.test(value)) return 'value looks like a JSON Web Token';
  if (BEARER_RE.test(value)) return 'value looks like a bearer credential';
  if (!CORRELATION_ID_KEYS.has(key) && UUID_RE.test(value)) {
    return 'value looks like a UUID, which is never a metric dimension';
  }
  return null;
}

/**
 * Copies ONLY the allow-listed keys out of `source`. Anything else is
 * dropped by construction. Pure; never throws; never mutates `source`; never
 * places a dropped or refused VALUE anywhere in its own output.
 *
 * `correlation` here is built from whatever `helm.trace_id` survived, so a
 * caller that only has a loose bag still gets a correlation block; use
 * `sentryTagsFromEnvelope` when the three ids are known separately.
 */
export function buildSentrySupabaseTags(
  source: Readonly<Record<string, unknown>>,
  traceIds?: SupabaseTraceIds,
): SentrySupabasePayload {
  const tags: Partial<Record<SentrySupabaseTagKey, string>> = {};
  const droppedKeys: string[] = [];
  const refusedValues: RefusedTagValue[] = [];

  for (const key of Object.keys(source)) {
    if (!ALLOWED.has(key)) {
      droppedKeys.push(key);
      continue;
    }
    const allowedKey = key as SentrySupabaseTagKey;
    const raw = source[key];

    if (raw === null || raw === undefined) continue;
    if (typeof raw !== 'string' && typeof raw !== 'number' && typeof raw !== 'boolean') {
      refusedValues.push({ key: allowedKey, reason: 'value is not a scalar' });
      continue;
    }

    const value = String(raw).trim();
    if (value.length === 0) continue;

    const reason = refuseReason(allowedKey, value);
    if (reason) {
      refusedValues.push({ key: allowedKey, reason });
      continue;
    }

    if (CORRELATION_ID_KEYS.has(allowedKey)) {
      // A correlation id gets a SHAPE check, never the free-text masker:
      // `sanitizeSupabaseFreeText` rewrites a UUID to `[id]`, which is
      // correct for a dimension and destroys the one field whose entire
      // purpose is to be joined on. The refusals above already rejected an
      // email or a token here.
      const traceValue = normalizeHelmTraceId(value);
      if (traceValue === null) {
        refusedValues.push({ key: allowedKey, reason: 'value is not a usable correlation id' });
        continue;
      }
      tags[allowedKey] = traceValue;
      continue;
    }

    // Belt and braces on top of the refusals above: the same masking every
    // other durable Supabase free-text field gets, so a shape neither the
    // refusal list nor the allow-list anticipated still cannot ride out
    // intact.
    const safe = sanitizeSupabaseFreeText(value, MAX_TAG_VALUE_CHARS);
    if (safe === null || safe.length === 0) {
      refusedValues.push({ key: allowedKey, reason: 'value did not survive sanitization' });
      continue;
    }
    tags[allowedKey] = safe;
  }

  const correlation = buildTraceCorrelation(
    traceIds ?? { sentryTraceId: null, w3cTraceId: null, helmTraceId: tags['helm.trace_id'] ?? null },
  );

  return { tags, correlation, droppedKeys, refusedValues };
}

/**
 * The normal entry point: maps the canonical envelope onto the ten
 * allow-listed keys, then routes them through `buildSentrySupabaseTags` so
 * there is exactly one place values are checked.
 *
 * `normalizedMessage`, `safeDetails` and `safeHint` are deliberately NOT
 * tags — they are message/context, and a free-text tag is an unbounded
 * cardinality dimension.
 */
export function sentryTagsFromEnvelope(
  envelope: SupabaseErrorEnvelope,
  traceIds: SupabaseTraceIds,
): SentrySupabasePayload {
  return buildSentrySupabaseTags(
    {
      'supabase.service': envelope.service,
      'supabase.operation': envelope.operation,
      'supabase.rpc': envelope.rpc,
      'supabase.relation': envelope.relation,
      'supabase.code': envelope.code,
      'postgres.sqlstate': envelope.sqlstate,
      'helm.feature': envelope.feature,
      'helm.action': envelope.action,
      'helm.trace_id': traceIds.helmTraceId ?? envelope.helmTraceId,
      release: envelope.releaseSha,
    },
    traceIds,
  );
}
