/**
 * render.mjs — turn a resolved Contract into markdown or JSON.
 *
 * The JSON form is the artifact a later invariant/journey validator (Phase D
 * of docs/ai-system/CONTROL_PLANE_IMPLEMENTATION_PLAN_2026-09-03.md, item
 * K.4.3) is meant to consume — see docs/generated/contracts/README.md.
 * Nothing here writes a test, lint rule, or runtime code path; compiling
 * INTO those forms is explicitly future work per that plan section.
 */

function truncate(text, max) {
  if (text.length <= max) return text;
  return `${text.slice(0, max).trimEnd()}\n…[truncated ${text.length - max} chars — see source]`;
}

function claimHeading(claim) {
  const parts = [claim.kind];
  if (claim.date) parts.push(claim.date);
  return parts.join(' · ');
}

function renderSourceLine(source) {
  const loc = source.line ? `${source.path}:${source.line}` : source.path;
  return source.heading ? `${loc} (${source.heading})` : loc;
}

function renderClaimMarkdown(claim, { maxTextChars = 500 } = {}) {
  const lines = [`- **[${claimHeading(claim)}]** ${truncate(claim.text.replace(/\n+/g, ' '), maxTextChars)}`];
  lines.push(`  - source: \`${renderSourceLine(claim.source)}\``);
  if (claim.sha) lines.push(`  - sha: \`${claim.sha}\``);
  return lines.join('\n');
}

function renderSupersededMarkdown(claim) {
  const s = claim.superseded;
  const lines = [
    `- **[${claimHeading(claim)}]** (confidence: ${s.confidence}) ${truncate(claim.text.replace(/\n+/g, ' '), 300)}`,
    `  - still appears at: \`${renderSourceLine(claim.source)}\``,
    `  - superseded because: ${s.reason} — ${s.evidence}`,
  ];
  if (s.matchedBy) lines.push(`  - note: ${s.matchedBy}`);
  return lines.join('\n');
}

export function renderMarkdown(contract) {
  const out = [];
  out.push(`# Contract: ${contract.feature_id}`);
  out.push('');
  out.push(`Generated by \`npm run contract:resolve -- --feature ${contract.requested_id}\` at anchor SHA \`${contract.anchor_sha}\`.`);
  if (contract.resolution.via !== 'direct') {
    out.push('');
    out.push(`> **Resolution note:** ${contract.resolution.note}`);
  }
  out.push('');
  out.push(
    `${contract.current_contract.length} current claim(s), ${contract.superseded_claims.length} superseded claim(s), ` +
      `from ${contract.sources_consulted.length} source(s).`,
  );

  out.push('');
  out.push('## Current contract');
  out.push('');
  if (contract.current_contract.length === 0) {
    out.push('_No claims extracted._');
  } else {
    const byKind = groupBy(contract.current_contract, (c) => c.kind);
    for (const [kind, claims] of byKind) {
      out.push(`### ${kind} (${claims.length})`);
      out.push('');
      for (const claim of claims) out.push(renderClaimMarkdown(claim));
      out.push('');
    }
  }

  out.push('## Superseded claims');
  out.push('');
  if (contract.superseded_claims.length === 0) {
    out.push('_None detected._');
  } else {
    const mechanical = contract.superseded_claims.filter((c) => c.superseded.confidence === 'mechanical');
    const structured = contract.superseded_claims.filter((c) => c.superseded.confidence === 'structured');
    const heuristic = contract.superseded_claims.filter((c) => c.superseded.confidence === 'heuristic');

    if (mechanical.length > 0) {
      out.push('### Mechanical (existence-verified — path or schema object confirmed absent)');
      out.push('');
      for (const claim of mechanical) out.push(renderSupersededMarkdown(claim));
      out.push('');
    }
    if (structured.length > 0) {
      out.push('### Structured (declared in an ADR `Supersedes:` field)');
      out.push('');
      for (const claim of structured) out.push(renderSupersededMarkdown(claim));
      out.push('');
    }
    if (heuristic.length > 0) {
      out.push(
        '### Heuristic (shared-vocabulary match on a ledger correction marker — ' +
          'a PROMPT to verify, not a verdict; confirm by reading both entries)',
      );
      out.push('');
      for (const claim of heuristic) out.push(renderSupersededMarkdown(claim));
      out.push('');
    }
  }

  out.push('## Sources consulted');
  out.push('');
  for (const s of contract.sources_consulted) out.push(`- \`${s.path}\` (${s.kind})`);

  return `${out.join('\n')}\n`;
}

function groupBy(items, keyFn) {
  const map = new Map();
  for (const item of items) {
    const key = keyFn(item);
    if (!map.has(key)) map.set(key, []);
    map.get(key).push(item);
  }
  return map;
}

export function renderJson(contract) {
  return `${JSON.stringify(contract, null, 2)}\n`;
}
