/**
 * Guards `extractEnums()` in scripts/regen-docs.mjs.
 *
 * Run: vitest (promoted explicitly in vitest.config.ts — this file is NOT
 * swept in by a `scripts/**` glob; the other files in this directory are
 * `node --test` files that no CI job runs).
 *
 * WHY THIS EXISTS
 *
 * From roughly 2026-02 until 2026-08-19, `memory/glossary.md` rendered
 * `**6 enums**` while the schema had 18. The block carries a
 * `DO NOT EDIT — regenerated by scripts/regen-docs.mjs` stamp, and CLAUDE.md
 * routes every session there for enum lookups — so "what values does
 * golf_expense_category accept?" answered "that enum does not exist," with the
 * strongest available trust signal attached.
 *
 * Nothing caught it. `docs:check` re-runs the generator and diffs the output
 * against the file, so it only ever compared the generator to itself and stayed
 * green. The regex was also untestable in practice, because importing
 * regen-docs.mjs used to execute main() and rewrite the docs as a side effect.
 *
 * The two defects, both in one regex
 * (`/^      (name):\s*((?:"[^"]*"\s*\|?\s*)+)/gm`):
 *
 *   1. LEADING-PIPE: Supabase emits long enums with the pipe at the start of
 *      each continuation line. The pattern only allowed a pipe AFTER a quoted
 *      value, so every multi-line enum failed outright.
 *   2. LASTINDEX SWALLOW: the trailing `\s*` consumed the newline and the next
 *      line's six-space indent, so the `^      ` anchor could not match the
 *      enum immediately following a match — losing single-line, well-formed
 *      enums too.
 *
 * Each case below is one of those defects, plus the emission shapes Supabase is
 * known to produce. Adding a shape here is cheaper than another six months of
 * confidently wrong answers.
 */

import { describe, expect, it } from 'vitest';

import { extractEnums } from '../regen-docs.mjs';

/** Wrap a raw Enums body in the minimum structure extractEnums navigates. */
const wrap = (body) => `  public: {\n    Enums: {\n${body}    }\n  }\n`;

describe('extractEnums', () => {
  it('reads single-line enums', () => {
    const out = extractEnums(
      wrap(`      a_kind: "x" | "y"\n      b_kind: "p" | "q"\n`)
    );
    expect(out.map((e) => e.name)).toEqual(['a_kind', 'b_kind']);
    expect(out[0].values).toEqual(['x', 'y']);
  });

  it('reads multi-line enums declared with a LEADING pipe (defect 1)', () => {
    const out = extractEnums(
      wrap(`      a_kind:\n        | "x"\n        | "y"\n        | "z"\n`)
    );
    expect(out).toHaveLength(1);
    expect(out[0].values).toEqual(['x', 'y', 'z']);
  });

  it('does not drop the enum immediately after a match (defect 2)', () => {
    // This is the exact shape that lost baseball_coach_type, program_type and
    // team_member_status: single-line, well-formed, and simply next in line.
    const out = extractEnums(
      wrap(
        `      a_kind: "x" | "y"\n      b_kind: "p" | "q"\n      c_kind: "m" | "n"\n`
      )
    );
    expect(out.map((e) => e.name)).toEqual(['a_kind', 'b_kind', 'c_kind']);
  });

  it('reads bracket/array emission', () => {
    // The `Constants` export at the bottom of database.ts uses this shape. It
    // is not what the Enums type block emits today, but it is the same
    // generator, and a shape change here previously meant silent loss.
    const out = extractEnums(
      wrap(`      a_kind: [\n        "x",\n        "y",\n      ]\n      b_kind: "p"\n`)
    );
    expect(out.map((e) => e.name)).toEqual(['a_kind', 'b_kind']);
    expect(out[0].values).toEqual(['x', 'y']);
  });

  it('handles the real mixed case: 3 shapes interleaved', () => {
    const out = extractEnums(
      wrap(
        `      a_kind: "x" | "y"\n` +
          `      b_kind:\n        | "p"\n        | "q"\n` +
          `      c_kind: "m"\n` +
          `      d_kind:\n        | "s"\n        | "t"\n`
      )
    );
    expect(out.map((e) => e.name)).toEqual([
      'a_kind',
      'b_kind',
      'c_kind',
      'd_kind',
    ]);
  });

  it('returns results sorted by name', () => {
    const out = extractEnums(wrap(`      z_kind: "a"\n      a_kind: "b"\n`));
    expect(out.map((e) => e.name)).toEqual(['a_kind', 'z_kind']);
  });

  it('THROWS rather than silently under-reporting', () => {
    // The whole point. A shape this parser cannot read must be a loud failure,
    // never a short list — a short list is indistinguishable from the truth
    // once it is rendered under a "DO NOT EDIT — regenerated" header.
    expect(() =>
      extractEnums(wrap(`      a_kind: "x"\n      b_kind: SomeUnquotedRef\n`))
    ).toThrow(/dropped 1 of 2 enums: b_kind/);
  });

  it('is a no-op when the public schema has no Enums block', () => {
    expect(extractEnums('  public: {\n    Tables: {\n    }\n  }\n')).toEqual([]);
  });

  it('anchors inside `public`, not the empty graphql_public schema', () => {
    // database.ts declares graphql_public FIRST with identically-indented
    // blocks; a bare indexOf locks onto it and reports an empty database.
    const src =
      `  graphql_public: {\n    Enums: {\n    }\n  }\n` +
      `  public: {\n    Enums: {\n      real_kind: "yes"\n    }\n  }\n`;
    expect(extractEnums(src).map((e) => e.name)).toEqual(['real_kind']);
  });
});
