import { execFileSync } from 'node:child_process';
import { RANKING_BASIS } from './rank.mjs';

function headSha(repoRoot) {
  try {
    return execFileSync('git', ['rev-parse', 'HEAD'], { cwd: repoRoot, encoding: 'utf-8' }).trim();
  } catch {
    return 'UNKNOWN';
  }
}

function shortSha(sha) {
  return sha === 'UNKNOWN' ? sha : sha.slice(0, 9);
}

/**
 * Build the JSON side-file: NOT config/control-plane-gaps.json, and never
 * written into it. That file's own $comment is explicit — "Nothing may be
 * listed here to make a red verifier green: the entry must describe a real
 * decision" and "Adding one is a decision, not a repair" — an automated
 * finding is neither of those until a human has reviewed it. The
 * id/owner/opened/scope/reason/closes_when field SHAPE is reused (Phase
 * K.4.5) because it is this repo's one existing "here is a named,
 * dated, owned thing to act on" vocabulary; the file target is not.
 */
export function buildFindingsJson({ repoRoot, classResults, rankedFindings, generatedAt }) {
  const sha = headSha(repoRoot);
  return {
    $comment: [
      'JANITOR-PROPOSED FINDINGS. This is NOT config/control-plane-gaps.json and',
      'must never be merged into it or auto-appended to it — that file records',
      'decisions a human has already made not to fix something',
      '("Adding one is a decision, not a repair" — its own $comment). Every entry',
      'below is a machine-generated PROPOSAL: read it, decide, and either open',
      'the small PR "closes_when" describes or (if declining) add a real',
      'ACKNOWLEDGED_GAP to config/control-plane-gaps.json yourself, by hand.',
      '',
      'Regenerate with: npm run janitor',
    ],
    generated_at: generatedAt,
    generated_at_sha: sha,
    ranking_basis: RANKING_BASIS,
    classes: classResults.map((r) => ({
      classId: r.classId,
      title: r.title,
      verdict: r.verdict,
      note: r.note ?? null,
      evidenceCommand: r.evidenceCommand,
      findingCount: r.verdict === 'FINDINGS' ? r.findings.length : 0,
    })),
    findings: rankedFindings.map((f) => ({
      id: f.id,
      owner: 'unassigned',
      opened: generatedAt.slice(0, 10),
      class: f.classId,
      scope: f.scope,
      reason: `[${f.classId}] ${f.summary}${f.detail ? ' — ' + f.detail : ''}`,
      closes_when: f.proposedPr,
      confidence: f.confidence,
      size_of_change: f.sizeOfChange,
    })),
  };
}

function verdictBadge(v) {
  if (v === 'FINDINGS') return '🔎 FINDINGS';
  if (v === 'ZERO_FINDINGS_VERIFIED') return '✅ ZERO_FINDINGS_VERIFIED';
  return '❔ NO_SIGNAL';
}

export function buildMarkdownReport({ repoRoot, classResults, rankedFindings, generatedAt }) {
  const sha = headSha(repoRoot);
  const short = shortSha(sha);
  const lines = [];

  lines.push('<!-- markdownlint-disable MD013 MD022 MD032 MD034 MD037 MD040 -->');
  lines.push('# Janitor entropy report');
  lines.push('');
  lines.push('GENERATED by `scripts/janitor/run.mjs` (`npm run janitor`). DO NOT EDIT by hand —');
  lines.push('regenerate it instead. This is a proposal surface, not a decision record:');
  lines.push('it is **not** `config/control-plane-gaps.json` and nothing here is auto-merged');
  lines.push('into that file. That file\'s own `$comment` says why: "Nothing may be listed');
  lines.push('here to make a red verifier green... Adding one is a decision, not a repair."');
  lines.push('Read a finding, decide, then either open the small PR its "Proposed PR" line');
  lines.push('describes, or add a real `ACKNOWLEDGED_GAP` to that file yourself if declining.');
  lines.push('');
  lines.push(`Anchor: \`${short}\` (record a SHA, not a date, per \`.claude/rules/shipping.md\` §1 —`);
  lines.push('run `git rev-list --count ' + short + '..HEAD` to see how stale this report is).');
  lines.push('');
  lines.push(`**Ranking basis:** ${RANKING_BASIS}`);
  lines.push('');

  lines.push('## Class coverage');
  lines.push('');
  lines.push(
    'Every finding class the Janitor knows about is listed here, including the ones with',
  );
  lines.push(
    'nothing to report — a class silently absent would look identical to a clean class,',
  );
  lines.push('which is exactly the failure this table exists to rule out.');
  lines.push('');
  lines.push('| Class | Verdict | Findings | Evidence command |');
  lines.push('| --- | --- | --- | --- |');
  for (const r of classResults) {
    const count = r.verdict === 'FINDINGS' ? r.findings.length : '—';
    lines.push(`| ${r.title} | ${verdictBadge(r.verdict)} | ${count} | \`${r.evidenceCommand}\` |`);
  }
  lines.push('');

  for (const r of classResults) {
    if (r.note) {
      lines.push(`- **${r.title}:** ${r.note}`);
    }
  }
  lines.push('');

  lines.push('## Ranked findings');
  lines.push('');
  if (rankedFindings.length === 0) {
    lines.push('No findings across any class this run.');
  } else {
    for (const f of rankedFindings) {
      lines.push(`### ${f.id} — ${f.summary}`);
      lines.push('');
      lines.push(`- **Class:** ${f.classTitle} (\`${f.classId}\`)`);
      lines.push(`- **Scope:** \`${f.scope}\``);
      lines.push(`- **Confidence:** ${f.confidence} · **Proposed change size:** ${f.sizeOfChange}`);
      if (f.detail) lines.push(`- **Detail:** ${f.detail}`);
      lines.push(`- **Proposed PR:** ${f.proposedPr}`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push(`Generated ${generatedAt} at \`${short}\`. Machine JSON: \`docs/generated/janitor-findings.json\`.`);
  lines.push('');

  return lines.join('\n');
}
