window.ROSTER = {
  team: 'Varsity', code: 'FINLEY-26',
  players: [
    { id: 'theo', role: 'Captain', major: 'Economics', course: 'Biltmore Forest CC', bday: 'Mar 3', since: 'Joined Aug 2023', about: 'Plays fast and talks everyone through the pre-round.', name: 'Theo Marchetti', year: 'Senior', cls: 2027, home: 'Asheville, NC', status: 'active', avg: 70.9, hcp: -0.8, rounds: 24, sg: 1.8, trend: [72, 71, 71, 70, 70, 71, 70], focus: 1, goals: 3, last: [['Oakmont CC', 'Oct 12', 70, -1], ['Pine Needles', 'Oct 11', 69, -3], ['Finley GC', 'Oct 4', 71, -1]], note: 'Improving' },
    { id: 'sofia', major: 'Kinesiology', course: 'Brackenridge Park', bday: 'Nov 21', since: 'Joined Aug 2023', about: 'Best ball-striker on the team. Keeps a yardage book for every course.', name: 'Sofia Alvarez', year: 'Senior', cls: 2027, home: 'San Antonio, TX', status: 'active', avg: 71.6, hcp: 1.9, rounds: 22, sg: 1.1, trend: [72, 72, 71, 72, 71, 71, 71], focus: 2, goals: 2, last: [['Oakmont CC', 'Oct 12', 71, 0], ['Finley GC', 'Oct 8', 72, 0], ['Finley GC', 'Oct 4', 71, -1]], note: 'Steady' },
    { id: 'ava', major: 'Environmental science', course: 'Hills GK', bday: 'Oct 18', since: 'Joined Jan 2025', about: 'Came over from Sweden mid-year. Birthday on Saturday.', name: 'Ava Lindqvist', year: 'Junior', cls: 2028, home: 'Gothenburg, SE', status: 'active', avg: 72.4, hcp: 2.4, rounds: 19, sg: 0.6, trend: [73, 74, 72, 72, 72, 73, 72], focus: 1, goals: 2, last: [['Oakmont CC', 'Oct 12', 72, 1], ['Finley GC', 'Oct 8', 73, 1], ['Finley GC', 'Oct 4', 72, 0]], note: 'Steady' },
    { id: 'jonah', major: 'Business', course: 'Carolina GC', bday: 'Jun 9', since: 'Joined Aug 2025', about: 'Long off the tee. Working on 125 to 150 with the wedges.', name: 'Jonah Okafor', year: 'Sophomore', cls: 2029, home: 'Charlotte, NC', status: 'active', avg: 74.1, hcp: 3.9, rounds: 21, sg: -0.9, trend: [72, 72, 73, 74, 75, 74, 75], focus: 2, goals: 1, last: [['Pine Needles', 'Oct 11', 76, 4], ['Finley GC', 'Oct 8', 75, 3], ['Finley GC', 'Oct 4', 74, 2]], note: 'Scoring up 2.1', attn: 'warning' },
    { id: 'eli', major: 'Biology', course: 'North Ridge CC', bday: 'Feb 14', since: 'Joined Aug 2024', about: 'Pre-med schedule. Labs on Wednesday afternoons.', name: 'Eli Brandt', year: 'Junior', cls: 2028, home: 'Raleigh, NC', status: 'active', avg: 74.8, hcp: 4.2, rounds: 14, sg: -0.4, trend: [74, 75, 74, 75, 75, 74, 75], focus: 0, goals: 0, last: [['Finley GC', 'Oct 5', 75, 3], ['Finley GC', 'Sep 28', 74, 2], ['Lonnie Poole', 'Sep 27', 75, 3]], note: 'No rounds in 9 days', attn: 'warning' },
    { id: 'priya', major: 'Statistics', course: 'Prestonwood CC', bday: 'Jul 30', since: 'Joined Aug 2026', about: 'Freshman. Tracks every putt and asks good questions.', name: 'Priya Natarajan', year: 'Freshman', cls: 2030, home: 'Cary, NC', status: 'active', avg: 75.2, hcp: 5.1, rounds: 16, sg: -1.4, trend: [78, 77, 77, 76, 75, 75, 74], focus: 1, goals: 2, last: [['Finley GC', 'Oct 10', 74, 2], ['Finley GC', 'Oct 8', 75, 3], ['Finley GC', 'Oct 4', 75, 3]], note: '4 rounds under average', attn: 'positive' },
    { id: 'luca', major: 'Undeclared', course: 'Golf Club Bologna', bday: 'Dec 2', since: 'Joined Sep 2026', about: 'Joined three weeks ago. Two rounds posted so far.', name: 'Luca Ferraro', year: 'Freshman', cls: 2030, home: 'Bologna, IT', status: 'active', avg: 76.3, hcp: 6.0, rounds: 2, sg: null, trend: [77, 76], focus: 0, goals: 1, last: [['Finley GC', 'Oct 8', 76, 4], ['Finley GC', 'Oct 1', 77, 5]], note: 'Early read · 2 rounds' },
    { id: 'mia', major: 'Nursing', course: 'Green Valley CC', bday: 'Apr 25', since: 'Joined Aug 2024', about: 'Out with a wrist injury. Cleared to chip, not to swing.', name: 'Mia Thornton', year: 'Junior', cls: 2028, home: 'Greenville, SC', status: 'inactive', avg: 73.8, hcp: 3.4, rounds: 9, sg: -0.2, trend: [74, 73, 74, 74, 73], focus: 0, goals: 0, last: [['Finley GC', 'Sep 12', 74, 2]], note: 'Medical · wrist' },
  ],
  requests: [
    { id: 'r1', name: 'Grace Liu', meta: 'Freshman · Class of 2030 · requested yesterday', hcp: '7.2' },
    { id: 'r2', name: 'Owen Park', meta: 'Sophomore · Class of 2029 · requested 3 days ago', hcp: '4.8' },
  ],
};
