#!/usr/bin/env node
/**
 * Auto-regen the inventory sections of memory/* docs.
 *
 * Why: memory/glossary.md and memory/projects/golfhelm.md contain
 * hand-curated narrative (role-based table groupings, feature
 * explanations, etc.) PLUS pure inventory lists (all tables, all
 * routes, all action files). The inventory rots the moment anyone
 * touches the schema or adds a page. This script regenerates only
 * the inventory, between AUTOGEN markers, leaving the narrative alone.
 *
 * Inventories regenerated:
 *   - memory/glossary.md       AUTOGEN:tables (all tables alphabetical)
 *   - memory/glossary.md       AUTOGEN:enums  (all enums + values)
 *   - memory/projects/golfhelm.md  AUTOGEN:routes
 *   - memory/projects/golfhelm.md  AUTOGEN:actions
 *   - memory/projects/golfhelm.md  AUTOGEN:hooks
 *
 * Sources of truth:
 *   - Tables + enums: src/lib/types/database.ts (auto-generated by
 *     npm run db:types from the live Supabase schema)
 *   - Routes: src/app under page.tsx files
 *   - Actions: src/app under actions/ directories
 *   - Hooks: src/hooks/**
 *
 * If a managed block doesn't exist in the target file yet, this
 * script appends it under a clear header. Existing blocks are
 * updated in place — hand-edits outside the markers are preserved.
 *
 * Run locally: npm run docs:regen
 * CI:          .github/workflows/docs-regen.yml on push to main
 *
 * Pure stdlib — uses only node:fs/promises and node:path. No
 * child_process, no shell, no network, no external deps.
 */

import { readFile, writeFile, readdir } from 'node:fs/promises';
import { join, relative, sep, posix } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = join(fileURLToPath(import.meta.url), '..', '..');
const DATABASE_TYPES = join(REPO_ROOT, 'src/lib/types/database.ts');
const APP_DIR = join(REPO_ROOT, 'src/app');
const HOOKS_DIR = join(REPO_ROOT, 'src/hooks');
const GLOSSARY = join(REPO_ROOT, 'memory/glossary.md');
const PROJECT_DOC = join(REPO_ROOT, 'memory/projects/golfhelm.md');

async function walk(dir, predicate) {
  const out = [];
  async function recurse(d) {
    let entries;
    try {
      entries = await readdir(d, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const full = join(d, entry.name);
      if (entry.isDirectory()) {
        if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue;
        await recurse(full);
      } else if (entry.isFile() && predicate(full)) {
        out.push(full);
      }
    }
  }
  await recurse(dir);
  return out.sort();
}

function toPosix(p) {
  return p.split(sep).join(posix.sep);
}

async function parseDatabaseTypes() {
  const src = await readFile(DATABASE_TYPES, 'utf8');
  const tables = extractTopLevelKeys(src, 'Tables');
  const views = extractTopLevelKeys(src, 'Views');
  const functions = extractTopLevelKeys(src, 'Functions');
  const enums = extractEnums(src);
  return { tables, views, functions, enums };
}

/**
 * database.ts declares the empty `graphql_public` schema BEFORE `public`, and
 * both nest identically-indented Tables/Views/Functions/Enums blocks — a bare
 * first-match indexOf locks onto graphql_public and reports an empty database.
 * Anchor every block search inside the `public` schema.
 */
function publicSchemaOffset(src) {
  const start = src.indexOf('  public: {');
  return start === -1 ? 0 : start;
}

function extractTopLevelKeys(src, blockName) {
  const blockStart = src.indexOf(`    ${blockName}: {`, publicSchemaOffset(src));
  if (blockStart === -1) return [];
  let depth = 0;
  let i = blockStart + `    ${blockName}: {`.length - 1;
  for (; i < src.length; i++) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}') {
      depth--;
      if (depth === 0) break;
    }
  }
  const blockText = src.slice(blockStart, i);
  const keys = [];
  const re = /^      ([a-z_][a-z0-9_]*):\s*[\{\(]/gm;
  let m;
  while ((m = re.exec(blockText)) !== null) {
    keys.push(m[1]);
  }
  return keys.sort();
}

function extractEnums(src) {
  const blockStart = src.indexOf('    Enums: {', publicSchemaOffset(src));
  if (blockStart === -1) return [];
  let depth = 0;
  let i = blockStart + '    Enums: {'.length - 1;
  for (; i < src.length; i++) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}') {
      depth--;
      if (depth === 0) break;
    }
  }
  const blockText = src.slice(blockStart, i);
  const enums = [];
  const re = /^      ([a-z_][a-z0-9_]*):\s*((?:"[^"]*"\s*\|?\s*)+)/gm;
  let m;
  while ((m = re.exec(blockText)) !== null) {
    const name = m[1];
    const values = [...m[2].matchAll(/"([^"]+)"/g)].map((x) => x[1]);
    enums.push({ name, values });
  }
  return enums.sort((a, b) => a.name.localeCompare(b.name));
}

async function findRoutes() {
  const pageFiles = await walk(
    APP_DIR,
    (f) => f.endsWith('/page.tsx') || f.endsWith('/page.ts'),
  );
  const routes = pageFiles.map((f) => {
    let rel = toPosix(relative(APP_DIR, f));
    rel = rel.replace(/\/page\.(tsx|ts)$/, '');
    rel = rel
      .split('/')
      .filter((seg) => !(seg.startsWith('(') && seg.endsWith(')')))
      .join('/');
    return '/' + rel;
  });
  return [...new Set(routes)].sort();
}

async function findActions() {
  const actionFiles = await walk(
    APP_DIR,
    (f) =>
      f.endsWith('.ts') &&
      f.includes(`${sep}actions${sep}`) &&
      !f.endsWith('.test.ts'),
  );
  return actionFiles.map((f) => toPosix(relative(REPO_ROOT, f))).sort();
}

async function findHooks() {
  const hookFiles = await walk(
    HOOKS_DIR,
    (f) =>
      f.endsWith('.ts') &&
      !f.endsWith('.test.ts') &&
      !f.endsWith('.d.ts'),
  );
  return hookFiles.map((f) => toPosix(relative(REPO_ROOT, f))).sort();
}

function replaceManagedBlock(content, blockName, newBody) {
  const startMarker = `<!-- AUTOGEN:${blockName}:start -->`;
  const endMarker = `<!-- AUTOGEN:${blockName}:end -->`;
  const generatedBlock =
    `${startMarker}\n` +
    `<!-- DO NOT EDIT — regenerated by scripts/regen-docs.mjs -->\n\n` +
    `${newBody.trim()}\n\n` +
    `${endMarker}`;

  const startIdx = content.indexOf(startMarker);
  const endIdx = content.indexOf(endMarker);

  if (startIdx === -1 || endIdx === -1) {
    const trailer = content.endsWith('\n') ? '\n' : '\n\n';
    return (
      content +
      trailer +
      `\n---\n\n## Auto-generated inventory: ${blockName}\n\n` +
      generatedBlock +
      '\n'
    );
  }

  return (
    content.slice(0, startIdx) +
    generatedBlock +
    content.slice(endIdx + endMarker.length)
  );
}

function renderTablesBody({ tables, views, functions }) {
  const parts = [
    `**${tables.length} tables**, ${views.length} views, ${functions.length} functions ` +
      `(source: \`src/lib/types/database.ts\`).`,
    '',
    '<details><summary>Full alphabetical table list</summary>',
    '',
    tables.map((t) => `- \`${t}\``).join('\n'),
    '',
    '</details>',
  ];
  if (views.length) {
    parts.push(
      '',
      `<details><summary>Views (${views.length})</summary>`,
      '',
      views.map((v) => `- \`${v}\``).join('\n'),
      '',
      '</details>',
    );
  }
  if (functions.length) {
    parts.push(
      '',
      `<details><summary>Database functions (${functions.length})</summary>`,
      '',
      functions.map((f) => `- \`${f}()\``).join('\n'),
      '',
      '</details>',
    );
  }
  return parts.join('\n');
}

function renderEnumsBody(enums) {
  if (!enums.length) return '_No enums found._';
  return [
    `**${enums.length} enums** (source: \`src/lib/types/database.ts\`).`,
    '',
    '| Enum | Values |',
    '|------|--------|',
    ...enums.map(
      (e) => `| \`${e.name}\` | ${e.values.map((v) => `\`${v}\``).join(', ')} |`,
    ),
  ].join('\n');
}

function renderRoutesBody(routes) {
  return [
    `**${routes.length} routes** (source: \`src/app/**/page.tsx\`).`,
    '',
    '<details><summary>Full alphabetical route list</summary>',
    '',
    routes.map((r) => `- \`${r}\``).join('\n'),
    '',
    '</details>',
  ].join('\n');
}

function renderActionsBody(actions) {
  return [
    `**${actions.length} server-action files** (source: \`src/app/**/actions/**/*.ts\`).`,
    '',
    '<details><summary>Full alphabetical action file list</summary>',
    '',
    actions.map((a) => `- \`${a}\``).join('\n'),
    '',
    '</details>',
  ].join('\n');
}

function renderHooksBody(hooks) {
  return [
    `**${hooks.length} custom hooks** (source: \`src/hooks/**/*.ts\`).`,
    '',
    '<details><summary>Full alphabetical hook list</summary>',
    '',
    hooks.map((h) => `- \`${h}\``).join('\n'),
    '',
    '</details>',
  ].join('\n');
}

async function main() {
  console.log('Regenerating inventory docs…');

  const [{ tables, views, functions, enums }, routes, actions, hooks] =
    await Promise.all([parseDatabaseTypes(), findRoutes(), findActions(), findHooks()]);

  console.log(
    `  Tables: ${tables.length}, Views: ${views.length}, ` +
      `Functions: ${functions.length}, Enums: ${enums.length}`,
  );
  console.log(`  Routes: ${routes.length}, Actions: ${actions.length}, Hooks: ${hooks.length}`);

  let glossary = await readFile(GLOSSARY, 'utf8');
  glossary = replaceManagedBlock(
    glossary,
    'tables',
    renderTablesBody({ tables, views, functions }),
  );
  glossary = replaceManagedBlock(glossary, 'enums', renderEnumsBody(enums));
  await writeFile(GLOSSARY, glossary);

  let project = await readFile(PROJECT_DOC, 'utf8');
  project = replaceManagedBlock(project, 'routes', renderRoutesBody(routes));
  project = replaceManagedBlock(project, 'actions', renderActionsBody(actions));
  project = replaceManagedBlock(project, 'hooks', renderHooksBody(hooks));
  await writeFile(PROJECT_DOC, project);

  console.log('Done.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
