/**
 * seed-baseball-demo-program.ts — Fixes #912.
 *
 * The public BaseballHelm demo ("Demo University Baseball", entered via
 * /baseball/demo) promises a "fully-populated" program but — once past the
 * Phase-1 seed (scripts/seed-baseball-demo.ts) — actually shows an empty
 * season: 0 games on record in Stats Center, 0 open risk flags, an empty
 * recruiting board, and a single stale practice on the calendar. This script
 * closes that gap for the SAME Phase-1 demo team, WITHOUT re-seeding org/
 * team/coach/roster (Phase-1 owns those).
 *
 * WHAT IT SEEDS (extends the demo team; see docs/seed/BASEBALLHELM_DEMO_DATA_CONTRACT.md):
 *   1. A believable, already-completed season: 20 baseball_games rows (17
 *      official + 3 scrimmage) spanning Feb–May of the "current" season
 *      year, each with box-score-level baseball_box_score_batting /
 *      baseball_box_score_pitching lines for the roster's 6 hitters + 2
 *      pitchers, generated by a deterministic simulator
 *      (src/lib/baseball/seed/demo-program-sim.ts) so per-player lines stay
 *      internally consistent game-to-game (same hitter is always the same
 *      hitter). baseball_player_season_stats is then derived via the SAME
 *      `recalculate_baseball_season_stats` RPC the app's own box-score save
 *      flow calls (games.ts's completeGameAndRecalculate) — never a
 *      hand-authored aggregate row, so it can never drift from the canonical
 *      derivation.
 *   2. 3 open (status='active') baseball_coach_insights risk flags, each
 *      citing real rows this script (or Phase-1) seeded — a workload flag on
 *      one pitcher, a cooling-off flag on the weakest bat, and a stale-
 *      outreach flag on two recruiting-board prospects.
 *   3. A recruiting board: 3 small "feeder" programs (a high school, a
 *      showcase org, a JUCO — organizations + baseball_teams + team members,
 *      clearly fictional / demo-only) and 8 recruit baseball_players rows
 *      (recruiting_activated=true, never 'college' player_type) added to
 *      baseball_watchlists across all 4 active pipeline stages (watchlist /
 *      high_priority / offer_extended / committed).
 *   4. A rolling lifting-session history: 8 baseball_lift_results per
 *      roster player (squat + bench, alternating, ~8 weeks back), reusing
 *      Phase-1's own exercises (no duplicate "Back Squat" entries).
 *   5. A rolling calendar: 7 more upcoming baseball_events (practices, a
 *      team meeting, and a fall exhibition game) anchored to THIS script's
 *      run date, plus 2 more baseball_practices (with blocks) so Practice
 *      Planner shows more than Phase-1's single practice.
 *
 * SAFETY / IDEMPOTENCY (same guarantees as scripts/seed-baseball-demo.ts):
 *   - Every row id is deterministic (`detId()`, sha1 under a fixed
 *     namespace DISTINCT from Phase-1's, so nothing here can ever collide
 *     with or overwrite a Phase-1 row by accident).
 *   - Every write is `.upsert({ onConflict })` — there is no `.delete()`
 *     anywhere in this file.
 *   - Season-game dates are computed from "now" (evergreen: always "the
 *     most recently completed spring"), so re-running this script in a
 *     later year still produces a season that reads as just-finished
 *     instead of silently going stale.
 *   - Scoped strictly to the Phase-1 demo team id + this script's own new
 *     ids. Nothing outside that scope is ever read or written.
 *   - Recruit auth users are looked up by email first and only created when
 *     missing — never deleted, never password-reset (unlike the two shared
 *     CI login identities Phase-1 force-resets).
 *
 * DEPENDS ON scripts/seed-baseball-demo.ts having run at least once — this
 * script re-derives the Phase-1 org/team/coach/roster ids from the same
 * namespace + keys (mirrors scripts/seed-baseball-lifting-demo.ts's
 * `p1Id()` pattern) rather than re-creating them. If Phase-1 hasn't run,
 * the FK-dependent writes below will fail loudly with a clear Postgres
 * foreign-key error — run scripts/seed-baseball-demo.ts --confirm first.
 *
 * SAFE BY DEFAULT — dry run unless --confirm is passed.
 *
 * Run (later, by a human — this PR ships the script REVIEWED-ONLY, it is
 * never executed by the agent that authored it):
 *   # Dry run (prints the plan, writes nothing):
 *   DOTENV_CONFIG_PATH=.env.local npx tsx -r dotenv/config scripts/seed-baseball-demo-program.ts
 *   # Actually seed:
 *   DOTENV_CONFIG_PATH=.env.local npx tsx -r dotenv/config scripts/seed-baseball-demo-program.ts --confirm
 *
 * Requires env: NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY.
 */
import 'dotenv/config';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { createHash } from 'node:crypto';
import {
  simulateGame,
  type HitterSkill,
  type PitcherSkill,
} from '../src/lib/baseball/seed/demo-program-sim';

// ---------------------------------------------------------------------------
// CI guard (mirrors scripts/seed-baseball-demo.ts) — fail loudly before any
// async work if the required Supabase credentials are missing.
// ---------------------------------------------------------------------------
function assertRequiredSeedEnv(): void {
  const required = {
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  } as const;
  for (const [name, value] of Object.entries(required)) {
    if (!value || !value.trim()) {
      console.error(`Missing required env var: ${name} — cannot seed the baseball demo program`);
      process.exit(1);
    }
  }
}
assertRequiredSeedEnv();

// ---------------------------------------------------------------------------
// Deterministic ids.
//
// NS_P1 re-derives scripts/seed-baseball-demo.ts's ids (org/team/coach/
// roster) — MUST stay byte-identical to that script's namespace + keys.
// NS is THIS script's own namespace for every new row it creates, so ids
// here can never collide with Phase-1 (or seed-baseball-lifting-demo.ts's
// own 'baseballhelm-demo-lifting-v1' namespace).
// ---------------------------------------------------------------------------
const NS_P1 = 'baseballhelm-demo-phase1';
const NS = 'baseballhelm-demo-program-v1';

function detIdIn(namespace: string, key: string): string {
  const h = createHash('sha1').update(`${namespace}:${key}`).digest('hex');
  const b = h.slice(0, 32).split('');
  b[12] = '5';
  b[16] = ((parseInt(b[16], 16) & 0x3) | 0x8).toString(16);
  const s = b.join('');
  return `${s.slice(0, 8)}-${s.slice(8, 12)}-${s.slice(12, 16)}-${s.slice(16, 20)}-${s.slice(20, 32)}`;
}
const detId = (key: string) => detIdIn(NS, key);
const p1Id = (key: string) => detIdIn(NS_P1, key);

const TEAM_ID = p1Id('team');
const COACH_ID = p1Id('coach');

// Phase-1 roster (byte-identical to ROSTER in scripts/seed-baseball-demo.ts —
// only the fields THIS script needs: position for def_position/lineup slotting
// and bats/throws for the recruit profiles' flavor is not needed here).
const ROSTER = [
  { key: 'p1', first: 'Marcus', last: 'Rodriguez', pos: 'SS' },
  { key: 'p2', first: 'Jake', last: 'Thompson', pos: 'C' },
  { key: 'p3', first: 'Caleb', last: 'Williams', pos: 'OF' },
  { key: 'p4', first: 'Ethan', last: 'Brooks', pos: 'P' },
  { key: 'p5', first: 'Noah', last: 'Mitchell', pos: '3B' },
  { key: 'p6', first: 'Liam', last: 'Harrison', pos: '2B' },
  { key: 'p7', first: 'Aiden', last: 'Clark', pos: 'P' },
  { key: 'p8', first: 'Owen', last: 'Davis', pos: 'OF' },
] as const;
type RosterKey = (typeof ROSTER)[number]['key'];
const posByKey: Record<RosterKey, string> = Object.fromEntries(
  ROSTER.map((p) => [p.key, p.pos]),
) as Record<RosterKey, string>;
const playerIdByKey: Record<RosterKey, string> = Object.fromEntries(
  ROSTER.map((p) => [p.key, p1Id(`player:${p.key}`)]),
) as Record<RosterKey, string>;

// Batting order (6 non-pitcher roster slots) + the 2 pitchers who split every
// game's innings (starter alternates so both accumulate starts + relief).
const HITTER_ORDER: RosterKey[] = ['p1', 'p6', 'p3', 'p5', 'p2', 'p8'];

const HITTER_SKILLS: Record<RosterKey extends 'p4' | 'p7' ? never : RosterKey, HitterSkill> = {
  p1: { avg: 0.342, hrPct: 0.1, xbhPct: 0.38, bbPct: 0.1, kPct: 0.14, speed: 0.55 }, // Rodriguez, SS — star, leadoff
  p2: { avg: 0.261, hrPct: 0.09, xbhPct: 0.32, bbPct: 0.07, kPct: 0.19, speed: 0.1 }, // Thompson, C
  p3: { avg: 0.318, hrPct: 0.05, xbhPct: 0.34, bbPct: 0.09, kPct: 0.13, speed: 0.7 }, // Williams, OF — speedster
  p5: { avg: 0.278, hrPct: 0.14, xbhPct: 0.42, bbPct: 0.08, kPct: 0.22, speed: 0.15 }, // Mitchell, 3B — power
  p6: { avg: 0.301, hrPct: 0.06, xbhPct: 0.3, bbPct: 0.12, kPct: 0.15, speed: 0.45 }, // Harrison, 2B — switch
  p8: { avg: 0.249, hrPct: 0.06, xbhPct: 0.28, bbPct: 0.09, kPct: 0.21, speed: 0.2 }, // Davis, OF — weakest bat
};
const PITCHER_SKILLS: Record<'p4' | 'p7', PitcherSkill> = {
  p4: { h9: 7.6, k9: 9.4, bb9: 2.6, eraTarget: 2.95 }, // Brooks — ace
  p7: { h9: 8.4, k9: 7.9, bb9: 3.4, eraTarget: 4.1 }, // Clark — workhorse, workload-flag candidate
};

// ---------------------------------------------------------------------------
// Date helpers.
// ---------------------------------------------------------------------------
const NOW = new Date();
function pad2(n: number): string {
  return String(n).padStart(2, '0');
}
/** "Evergreen" season year: the most recently completed spring. College
 * seasons run roughly Feb–June, so before June 1 of `year` that spring
 * hasn't happened yet — fall back to the PRIOR year's season. */
const SEASON_YEAR = NOW.getUTCMonth() >= 5 ? NOW.getUTCFullYear() : NOW.getUTCFullYear() - 1;
function seasonDate(month1to12: number, day: number): string {
  return `${SEASON_YEAR}-${pad2(month1to12)}-${pad2(day)}`;
}
function isoDaysFromNow(days: number): string {
  const d = new Date(NOW);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString();
}
function isoDaysAgo(days: number): string {
  return isoDaysFromNow(-days);
}

// ---------------------------------------------------------------------------
// Upsert wrapper + counters (identical shape to scripts/seed-baseball-demo.ts).
// ---------------------------------------------------------------------------
type Counts = Record<string, number>;
const counts: Counts = {};
let DRY = false;
let supabase: SupabaseClient;
const skipped: string[] = [];

async function upsert(table: string, rows: readonly unknown[], conflict = 'id') {
  if (rows.length === 0) return;
  counts[table] = (counts[table] ?? 0) + rows.length;
  if (DRY) return;
  const { error } = await supabase.from(table).upsert(rows as never, { onConflict: conflict });
  if (error) {
    const msg = error.message || '';
    if (
      /could not find the table|schema cache|does not exist|could not find the '.*' column|violates not-null constraint|violates check constraint/i.test(
        msg,
      )
    ) {
      delete counts[table];
      skipped.push(`${table} — ${msg}`);
      console.warn(`  ⚠ skipped ${table} (schema not present yet): ${msg}`);
      return;
    }
    throw new Error(`upsert ${table} failed: ${msg}`);
  }
}

const DEMO_DOMAIN = 'baseballhelmdemo.com';
const DEMO_PASSWORD = 'BaseballDemo2026';

async function ensureAuthUser(email: string): Promise<{ userId: string | null; created: boolean }> {
  const { data: existing } = await supabase
    .from('users')
    .select('id')
    .ilike('email', email)
    .maybeSingle();
  if (existing) return { userId: existing.id as string, created: false };
  if (DRY) return { userId: null, created: false };
  const { data, error } = await supabase.auth.admin.createUser({
    email,
    password: DEMO_PASSWORD,
    email_confirm: true,
  });
  if (error || !data?.user) throw new Error(`createUser failed for ${email}: ${error?.message}`);
  return { userId: data.user.id, created: true };
}

// ---------------------------------------------------------------------------
// Season schedule — 20 games (17 official + 3 scrimmage), Feb–May of
// SEASON_YEAR. Opponent names are all fictional (no real-school names), same
// convention as "Demo University" / "Demo Conference" elsewhere in this seed.
// ---------------------------------------------------------------------------
interface ScheduledGame {
  month: number;
  day: number;
  opponent: string;
  homeAway: 'home' | 'away';
  gameType: 'game' | 'scrimmage';
}
const SCHEDULE: ScheduledGame[] = [
  { month: 2, day: 8, opponent: 'Sable Point', homeAway: 'home', gameType: 'scrimmage' },
  { month: 2, day: 14, opponent: 'Coastal Ridge', homeAway: 'home', gameType: 'game' },
  { month: 2, day: 15, opponent: 'Coastal Ridge', homeAway: 'home', gameType: 'game' },
  { month: 2, day: 21, opponent: 'Blue Harbor State', homeAway: 'away', gameType: 'scrimmage' },
  { month: 2, day: 28, opponent: 'Northgate', homeAway: 'away', gameType: 'game' },
  { month: 3, day: 1, opponent: 'Northgate', homeAway: 'away', gameType: 'game' },
  { month: 3, day: 7, opponent: 'Cedar Valley State', homeAway: 'home', gameType: 'game' },
  { month: 3, day: 8, opponent: 'Cedar Valley State', homeAway: 'home', gameType: 'game' },
  { month: 3, day: 14, opponent: 'Union Springs', homeAway: 'away', gameType: 'game' },
  { month: 3, day: 15, opponent: 'Union Springs', homeAway: 'away', gameType: 'game' },
  { month: 3, day: 21, opponent: 'Highland Tech', homeAway: 'home', gameType: 'scrimmage' },
  { month: 3, day: 28, opponent: 'Prairie Crossing', homeAway: 'home', gameType: 'game' },
  { month: 3, day: 29, opponent: 'Prairie Crossing', homeAway: 'home', gameType: 'game' },
  { month: 4, day: 4, opponent: 'Silver Creek', homeAway: 'away', gameType: 'game' },
  { month: 4, day: 11, opponent: 'Maple Hollow State', homeAway: 'home', gameType: 'game' },
  { month: 4, day: 12, opponent: 'Maple Hollow State', homeAway: 'home', gameType: 'game' },
  { month: 4, day: 18, opponent: 'Redstone', homeAway: 'away', gameType: 'game' },
  { month: 4, day: 25, opponent: 'Ashford', homeAway: 'home', gameType: 'game' },
  { month: 4, day: 26, opponent: 'Ashford', homeAway: 'home', gameType: 'game' },
  { month: 5, day: 2, opponent: 'Ironwood State', homeAway: 'away', gameType: 'game' },
];

// ---------------------------------------------------------------------------
// Recruiting board — 3 fictional feeder programs + 8 recruits.
// ---------------------------------------------------------------------------
type FeederOrgKey = 'hs' | 'sc' | 'jc';
const FEEDER_ORGS: Record<
  FeederOrgKey,
  { name: string; type: 'high_school' | 'showcase' | 'juco'; teamName: string; joinCode: string; city: string; state: string }
> = {
  hs: {
    name: 'Cypress Ridge High School',
    type: 'high_school',
    teamName: 'Cypress Ridge High School Baseball',
    joinCode: 'DEMOHS1',
    city: 'Ridgeview',
    state: 'NC',
  },
  sc: {
    name: 'Lakeview Showcase Academy',
    type: 'showcase',
    teamName: 'Lakeview Showcase Academy Baseball',
    joinCode: 'DEMOSC1',
    city: 'Lakeview',
    state: 'FL',
  },
  jc: {
    name: 'Tri-County Community College',
    type: 'juco',
    teamName: 'Tri-County Community College Baseball',
    joinCode: 'DEMOJC1',
    city: 'Millbrook',
    state: 'TX',
  },
};

type PipelineStage = 'watchlist' | 'high_priority' | 'offer_extended' | 'committed';
interface RecruitDef {
  key: string;
  first: string;
  last: string;
  org: FeederOrgKey;
  pos: string;
  bats: 'L' | 'R' | 'S';
  throws: 'L' | 'R';
  gradYear: number;
  jersey: number;
  exitVelo?: number;
  pitchVelo?: number;
  sixtyTime?: number;
  popTime?: number;
  armStrength?: number;
  gpa: number;
  stage: PipelineStage;
  source: string;
  tags: string[];
  fitScore: number;
  priority: 0 | 1;
  addedDaysAgo: number;
  lastContactDaysAgo: number;
  notes: string;
}
const RECRUITS: RecruitDef[] = [
  {
    key: 'r1', first: 'Tyler', last: 'Ramirez', org: 'hs', pos: 'SS', bats: 'R', throws: 'R',
    gradYear: 2027, jersey: 2, exitVelo: 94, sixtyTime: 6.7, armStrength: 88, gpa: 3.6,
    stage: 'high_priority', source: 'showcase', tags: ['bat-first', 'middle-infield'],
    fitScore: 88, priority: 1, addedDaysAgo: 62, lastContactDaysAgo: 6,
    notes: 'Plus bat speed, needs to add strength. Projects as an everyday SS in two years.',
  },
  {
    key: 'r2', first: 'Jordan', last: 'Blake', org: 'hs', pos: 'P', bats: 'R', throws: 'R',
    gradYear: 2027, jersey: 15, pitchVelo: 89, gpa: 3.4,
    stage: 'watchlist', source: 'film', tags: ['projectable-arm'],
    fitScore: 74, priority: 0, addedDaysAgo: 45, lastContactDaysAgo: 21,
    notes: 'Fastball ticking up; secondary pitches still inconsistent. Follow up overdue.',
  },
  {
    key: 'r3', first: 'DeShawn', last: 'Carter', org: 'sc', pos: 'OF', bats: 'L', throws: 'L',
    gradYear: 2028, jersey: 8, exitVelo: 96, sixtyTime: 6.5, gpa: 3.2,
    stage: 'offer_extended', source: 'camp', tags: ['power-speed'],
    fitScore: 91, priority: 1, addedDaysAgo: 90, lastContactDaysAgo: 4,
    notes: 'Offer extended after fall camp. Waiting on an official-visit date.',
  },
  {
    key: 'r4', first: 'Mason', last: 'Cole', org: 'jc', pos: 'C', bats: 'R', throws: 'R',
    gradYear: 2027, jersey: 21, popTime: 1.95, exitVelo: 90, gpa: 3.0,
    stage: 'committed', source: 'referral', tags: ['transfer', 'catcher'],
    fitScore: 95, priority: 1, addedDaysAgo: 120, lastContactDaysAgo: 2,
    notes: 'Verbally committed for the transfer class. Framing and arm both plus.',
  },
  {
    key: 'r5', first: 'Ryan', last: 'Ferguson', org: 'hs', pos: 'P', bats: 'L', throws: 'L',
    gradYear: 2028, jersey: 33, pitchVelo: 86, gpa: 3.8,
    stage: 'watchlist', source: 'film', tags: ['lefty', 'academic'],
    fitScore: 70, priority: 0, addedDaysAgo: 30, lastContactDaysAgo: 10,
    notes: 'Young lefty with a strong academic profile. Revisit next spring.',
  },
  {
    key: 'r6', first: 'Andre', last: 'Simmons', org: 'sc', pos: '3B', bats: 'R', throws: 'R',
    gradYear: 2027, jersey: 11, exitVelo: 92, armStrength: 90, gpa: 3.1,
    stage: 'high_priority', source: 'showcase', tags: ['corner-power'],
    fitScore: 85, priority: 1, addedDaysAgo: 55, lastContactDaysAgo: 5,
    notes: 'Big arm at third; power still developing. Top target for the class.',
  },
  {
    key: 'r7', first: 'Kevin', last: 'Nakamura', org: 'hs', pos: '2B', bats: 'R', throws: 'R',
    gradYear: 2029, jersey: 4, exitVelo: 88, sixtyTime: 6.6, gpa: 3.9,
    stage: 'watchlist', source: 'referral', tags: ['early-look', 'academic'],
    fitScore: 68, priority: 0, addedDaysAgo: 20, lastContactDaysAgo: 19,
    notes: 'Early look via a coaching contact. Keep on the radar; follow up overdue.',
  },
  {
    key: 'r8', first: 'Miguel', last: 'Ortiz', org: 'jc', pos: 'P', bats: 'R', throws: 'R',
    gradYear: 2027, jersey: 19, pitchVelo: 91, gpa: 2.9,
    stage: 'offer_extended', source: 'camp', tags: ['transfer', 'power-arm'],
    fitScore: 89, priority: 1, addedDaysAgo: 40, lastContactDaysAgo: 3,
    notes: 'Offer extended. Weighing the MLB Draft against transferring in.',
  },
];

// ===========================================================================
async function main() {
  const confirmed = process.argv.includes('--confirm');
  DRY = !confirmed;
  const url = (process.env.NEXT_PUBLIC_SUPABASE_URL ?? '').trim();
  const key = (process.env.SUPABASE_SERVICE_ROLE_KEY ?? '').trim();
  supabase = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });

  if (DRY) {
    console.log('[DRY RUN] No flag passed — printing the seed plan, writing NOTHING.');
    console.log('[DRY RUN] Re-run with --confirm to actually seed.\n');
  }
  console.log(
    `${DRY ? '[DRY RUN] ' : ''}Populating BaseballHelm demo program (team ${TEAM_ID.slice(0, 8)}, season ${SEASON_YEAR})`,
  );

  // ==========================================================================
  // SECTION A — Season: games + box scores + season-stat recalculation.
  // ==========================================================================
  const gamesRows: Record<string, unknown>[] = [];
  const battingRows: Record<string, unknown>[] = [];
  const pitchingRows: Record<string, unknown>[] = [];

  SCHEDULE.forEach((g, index) => {
    const gameId = detId(`game:${index}`);
    const dateStr = seasonDate(g.month, g.day);
    const startsWithP4 = index % 2 === 0;
    const starterKey: 'p4' | 'p7' = startsWithP4 ? 'p4' : 'p7';
    const relieverKey: 'p4' | 'p7' = startsWithP4 ? 'p7' : 'p4';

    const sim = simulateGame({
      gameKey: `${TEAM_ID}:${gameId}`,
      hitters: HITTER_ORDER.map((k) => ({ key: k, skill: HITTER_SKILLS[k as Exclude<RosterKey, 'p4' | 'p7'>] })),
      starter: { key: starterKey, skill: PITCHER_SKILLS[starterKey] },
      reliever: { key: relieverKey, skill: PITCHER_SKILLS[relieverKey] },
    });

    gamesRows.push({
      id: gameId,
      team_id: TEAM_ID,
      game_date: dateStr,
      game_type: g.gameType,
      opponent_name: g.opponent,
      location: g.homeAway === 'home' ? 'Demo Field' : `${g.opponent} Ballpark`,
      home_away: g.homeAway,
      our_score: sim.ourScore,
      opponent_score: sim.opponentScore,
      innings_played: 9,
      status: 'completed',
      created_by: COACH_ID,
    });

    for (const line of sim.batting) {
      battingRows.push({
        id: detId(`bat:${index}:${line.key}`),
        game_id: gameId,
        player_id: playerIdByKey[line.key as RosterKey],
        team_id: TEAM_ID,
        batting_order: line.battingOrder,
        ab: line.ab,
        r: line.r,
        h: line.h,
        doubles: line.doubles,
        triples: line.triples,
        hr: line.hr,
        rbi: line.rbi,
        bb: line.bb,
        k: line.k,
        sb: line.sb,
        cs: line.cs,
        hbp: line.hbp,
        sac: line.sac,
        sf: line.sf,
        def_position: posByKey[line.key as RosterKey],
      });
    }
    for (const line of sim.pitching) {
      pitchingRows.push({
        id: detId(`pit:${index}:${line.key}`),
        game_id: gameId,
        player_id: playerIdByKey[line.key as RosterKey],
        team_id: TEAM_ID,
        ip: line.ip,
        h: line.h,
        r: line.r,
        er: line.er,
        bb: line.bb,
        k: line.k,
        hr: line.hr,
        result: line.result,
        gs: line.isStarter ? 1 : 0,
        gf: line.isStarter ? 0 : 1,
      });
    }
  });

  await upsert('baseball_games', gamesRows);
  await upsert('baseball_box_score_batting', battingRows, 'game_id,player_id');
  await upsert('baseball_box_score_pitching', pitchingRows, 'game_id,player_id');

  if (!DRY) {
    for (const p of ROSTER) {
      const { error } = await supabase.rpc('recalculate_baseball_season_stats', {
        p_player_id: playerIdByKey[p.key],
        p_team_id: TEAM_ID,
        p_season_year: SEASON_YEAR,
      });
      if (error) {
        console.warn(`  ⚠ season recalc failed for ${p.key} (${p.first} ${p.last}): ${error.message}`);
      }
    }
  } else {
    console.log(`  [DRY RUN] would recalc season stats for ${ROSTER.length} players (season ${SEASON_YEAR})`);
  }

  // ==========================================================================
  // SECTION B — Risk flags: 3 open (status='active') coach insights.
  // ==========================================================================
  await upsert('baseball_coach_insights', [
    {
      id: detId('insight:workload'),
      team_id: TEAM_ID,
      coach_id: COACH_ID,
      player_id: playerIdByKey.p7,
      insight_type: 'workload',
      title: 'Aiden Clark’s workload is climbing',
      body: 'Innings and pitch counts over recent relief outings are trending up while his walk rate has crept alongside them — worth a lighter bullpen day before the next series.',
      priority: 'high',
      status: 'active',
      source_refs: [
        { table: 'baseball_box_score_pitching', sample_n: 10, confidence: 0.72, label: 'Season pitching lines (box score)' },
      ],
      confidence: 0.72,
      lifecycle_state: 'detected',
      player_visible: false,
      generated_by: 'demo_seed.workload_trend',
      dedupe_key: `${TEAM_ID}:workload_trend:${playerIdByKey.p7}`,
      last_generated_at: isoDaysAgo(0),
      metadata: {},
    },
    {
      id: detId('insight:cooling'),
      team_id: TEAM_ID,
      coach_id: COACH_ID,
      player_id: playerIdByKey.p8,
      insight_type: 'performance_trend',
      title: 'Owen Davis has cooled at the plate',
      body: 'Batting average over the last several logged games is running below his season line — a mechanics check or a lineup breather may help reset the swing.',
      priority: 'medium',
      status: 'active',
      source_refs: [
        { table: 'baseball_box_score_batting', sample_n: 5, confidence: 0.68, label: 'Last 5 games (box score)' },
      ],
      confidence: 0.68,
      lifecycle_state: 'detected',
      player_visible: false,
      generated_by: 'demo_seed.performance_trend',
      dedupe_key: `${TEAM_ID}:performance_trend:${playerIdByKey.p8}`,
      last_generated_at: isoDaysAgo(1),
      metadata: {},
    },
    {
      id: detId('insight:recruiting-stale'),
      team_id: TEAM_ID,
      coach_id: COACH_ID,
      player_id: null,
      insight_type: 'recruiting',
      title: 'Two recruits have gone quiet',
      body: 'Jordan Blake and Kevin Nakamura haven’t been contacted in over two weeks and are both still in an early pipeline stage — reach out before the file goes cold.',
      priority: 'medium',
      status: 'active',
      source_refs: [
        { table: 'baseball_watchlists', sample_n: 2, confidence: 0.6, label: 'Pipeline last-contact dates' },
      ],
      confidence: 0.6,
      lifecycle_state: 'detected',
      player_visible: false,
      generated_by: 'demo_seed.recruiting_stale_contact',
      dedupe_key: `${TEAM_ID}:recruiting_stale_contact`,
      last_generated_at: isoDaysAgo(0),
      metadata: {},
    },
  ]);

  // ==========================================================================
  // SECTION C — Recruiting board: 3 feeder programs + 8 recruits + watchlist.
  // ==========================================================================
  const feederOrgId: Record<FeederOrgKey, string> = {
    hs: detId('org:feeder-hs'),
    sc: detId('org:feeder-sc'),
    jc: detId('org:feeder-jc'),
  };
  const feederTeamId: Record<FeederOrgKey, string> = {
    hs: detId('team:feeder-hs'),
    sc: detId('team:feeder-sc'),
    jc: detId('team:feeder-jc'),
  };

  await upsert(
    'organizations',
    (Object.keys(FEEDER_ORGS) as FeederOrgKey[]).map((k) => ({
      id: feederOrgId[k],
      name: FEEDER_ORGS[k].name,
      type: FEEDER_ORGS[k].type,
      location_city: FEEDER_ORGS[k].city,
      location_state: FEEDER_ORGS[k].state,
      description: 'BaseballHelm demo feeder program (recruiting-board source, safe to ignore in production lists).',
    })),
  );
  await upsert(
    'baseball_teams',
    (Object.keys(FEEDER_ORGS) as FeederOrgKey[]).map((k) => ({
      id: feederTeamId[k],
      organization_id: feederOrgId[k],
      name: FEEDER_ORGS[k].teamName,
      team_type: FEEDER_ORGS[k].type,
      join_code: FEEDER_ORGS[k].joinCode,
    })),
  );

  const recruitPlayerRows: Record<string, unknown>[] = [];
  const recruitMemberRows: Record<string, unknown>[] = [];
  const watchlistRows: Record<string, unknown>[] = [];

  for (const r of RECRUITS) {
    const email = `recruit-${r.key}@${DEMO_DOMAIN}`;
    const auth = await ensureAuthUser(email);
    const pid = detId(`recruit:${r.key}`);

    recruitPlayerRows.push({
      id: pid,
      user_id: auth.userId,
      player_type: FEEDER_ORGS[r.org].type,
      recruiting_activated: true,
      recruiting_activated_at: isoDaysAgo(r.addedDaysAgo),
      first_name: r.first,
      last_name: r.last,
      email,
      primary_position: r.pos,
      bats: r.bats,
      throws: r.throws,
      grad_year: r.gradYear,
      exit_velo: r.exitVelo ?? null,
      pitch_velo: r.pitchVelo ?? null,
      sixty_time: r.sixtyTime ?? null,
      pop_time: r.popTime ?? null,
      arm_strength: r.armStrength ?? null,
      gpa: r.gpa,
      city: FEEDER_ORGS[r.org].city,
      state: FEEDER_ORGS[r.org].state,
      high_school_name: r.org === 'jc' ? null : FEEDER_ORGS[r.org].name,
      high_school_city: r.org === 'jc' ? null : FEEDER_ORGS[r.org].city,
      high_school_state: r.org === 'jc' ? null : FEEDER_ORGS[r.org].state,
      about_me: r.notes,
      onboarding_completed: true,
      profile_completion_percent: 90,
    });
    recruitMemberRows.push({
      id: detId(`recruit-member:${r.key}`),
      team_id: feederTeamId[r.org],
      player_id: pid,
      status: 'active',
      jersey_number: r.jersey,
      position: r.pos,
      joined_at: isoDaysAgo(r.addedDaysAgo + 30),
    });
    watchlistRows.push({
      id: detId(`watchlist:${r.key}`),
      coach_id: COACH_ID,
      player_id: pid,
      pipeline_stage: r.stage,
      priority: r.priority,
      fit_score: r.fitScore,
      source: r.source,
      tags: r.tags,
      notes: r.notes,
      added_at: isoDaysAgo(r.addedDaysAgo),
      last_contact: isoDaysAgo(r.lastContactDaysAgo),
    });
  }

  await upsert('baseball_players', recruitPlayerRows);
  await upsert('baseball_team_members', recruitMemberRows);
  await upsert('baseball_watchlists', watchlistRows, 'coach_id,player_id');

  // ==========================================================================
  // SECTION D — Rolling lifting-session history (reuses Phase-1's exercises).
  // ==========================================================================
  const squatExerciseId = p1Id('ex:squat');
  const benchExerciseId = p1Id('ex:bench');
  const liftResultRows: Record<string, unknown>[] = [];
  for (const p of ROSTER) {
    const pid = playerIdByKey[p.key];
    // 8 sessions per player, alternating squat/bench, roughly weekly for the
    // last 8 weeks, with a small deterministic weight progression.
    for (let week = 0; week < 8; week++) {
      const isSquat = week % 2 === 0;
      const exerciseId = isSquat ? squatExerciseId : benchExerciseId;
      const baseWeight = isSquat ? 225 : 155;
      const jitter = ((week * 7 + p.key.charCodeAt(1)) % 5) - 2; // small, deterministic -2..2
      liftResultRows.push({
        id: detId(`lift-history:${p.key}:${week}`),
        team_id: TEAM_ID,
        player_id: pid,
        exercise_id: exerciseId,
        performed_at: isoDaysAgo(7 * (8 - week) + 3),
        sets: isSquat ? 4 : 3,
        reps: isSquat ? 5 : 8,
        weight: baseWeight + Math.floor(week / 2) * 5 + jitter,
        rpe: 6.5 + ((week + (isSquat ? 0 : 1)) % 4) * 0.5,
        source: 'manual',
      });
    }
  }
  await upsert('baseball_lift_results', liftResultRows);

  // ==========================================================================
  // SECTION E — Rolling calendar: more upcoming events + 2 more practices.
  // ==========================================================================
  const practiceEvent2Id = detId('event:practice-2');
  const practiceEvent3Id = detId('event:practice-3');
  await upsert('baseball_events', [
    { id: practiceEvent2Id, team_id: TEAM_ID, created_by: COACH_ID, title: 'Team Practice — Infield/Outfield + Live BP', event_type: 'practice', location: 'Demo Field', start_time: isoDaysFromNow(3), end_time: isoDaysFromNow(3), is_mandatory: true },
    { id: detId('event:meeting-2'), team_id: TEAM_ID, created_by: COACH_ID, title: 'Team Meeting — Fall Program Planning', event_type: 'meeting', location: 'Film Room', start_time: isoDaysFromNow(5), end_time: isoDaysFromNow(5), is_mandatory: true },
    { id: practiceEvent3Id, team_id: TEAM_ID, created_by: COACH_ID, title: 'Team Practice — Bullpens + Baserunning', event_type: 'practice', location: 'Demo Field', start_time: isoDaysFromNow(8), end_time: isoDaysFromNow(8), is_mandatory: true },
    { id: detId('event:lift-1'), team_id: TEAM_ID, created_by: COACH_ID, title: 'Summer Strength & Conditioning', event_type: 'practice', location: 'Weight Room', start_time: isoDaysFromNow(10), end_time: isoDaysFromNow(10), is_mandatory: false },
    { id: detId('event:practice-4'), team_id: TEAM_ID, created_by: COACH_ID, title: 'Team Practice — Defensive Fundamentals', event_type: 'practice', location: 'Demo Field', start_time: isoDaysFromNow(15), end_time: isoDaysFromNow(15), is_mandatory: true },
    { id: detId('event:practice-5'), team_id: TEAM_ID, created_by: COACH_ID, title: 'Team Practice — Live BP + Scout Prep', event_type: 'practice', location: 'Demo Field', start_time: isoDaysFromNow(19), end_time: isoDaysFromNow(19), is_mandatory: true },
    { id: detId('event:exhibition-1'), team_id: TEAM_ID, created_by: COACH_ID, title: 'Fall Exhibition vs Westfield', event_type: 'game', location: 'Demo Field', start_time: isoDaysFromNow(26), end_time: isoDaysFromNow(26), is_mandatory: true },
  ]);

  const practice2Id = detId('practice:2');
  const practice3Id = detId('practice:3');
  await upsert('baseball_practices', [
    { id: practice2Id, team_id: TEAM_ID, event_id: practiceEvent2Id, title: 'Infield/Outfield + Live BP', focus: 'Defensive reads, live at-bats for the everyday lineup', status: 'published', published_at: isoDaysAgo(0) },
    { id: practice3Id, team_id: TEAM_ID, event_id: practiceEvent3Id, title: 'Bullpens + Baserunning', focus: 'Arm care progressions, secondary-lead work', status: 'published', published_at: isoDaysAgo(0) },
  ]);
  await upsert('baseball_practice_blocks', [
    { id: detId('block:p2-1'), team_id: TEAM_ID, practice_id: practice2Id, start_offset_min: 0, duration_min: 15, activity: 'Dynamic warmup', location: 'Outfield', coach_owner_id: COACH_ID },
    { id: detId('block:p2-2'), team_id: TEAM_ID, practice_id: practice2Id, start_offset_min: 15, duration_min: 40, activity: 'Infield/outfield defense', location: 'Infield', coach_owner_id: COACH_ID },
    { id: detId('block:p2-3'), team_id: TEAM_ID, practice_id: practice2Id, start_offset_min: 55, duration_min: 45, activity: 'Live batting practice', location: 'Cage + field', coach_owner_id: COACH_ID },
    { id: detId('block:p3-1'), team_id: TEAM_ID, practice_id: practice3Id, start_offset_min: 0, duration_min: 15, activity: 'Dynamic warmup + arm care', location: 'Outfield', coach_owner_id: COACH_ID },
    { id: detId('block:p3-2'), team_id: TEAM_ID, practice_id: practice3Id, start_offset_min: 15, duration_min: 40, activity: 'Bullpens', location: 'Pen', coach_owner_id: COACH_ID },
    { id: detId('block:p3-3'), team_id: TEAM_ID, practice_id: practice3Id, start_offset_min: 55, duration_min: 30, activity: 'Baserunning + secondary leads', location: 'Infield', coach_owner_id: COACH_ID },
  ]);

  // --- Report -------------------------------------------------------------
  console.log(`\n${DRY ? '[DRY RUN] would seed' : 'Seeded'} rows:`);
  for (const [t, n] of Object.entries(counts)) console.log(`  ${t.padEnd(34)} ${n}`);
  if (skipped.length) {
    console.log('\nSkipped (schema not present yet):');
    for (const s of skipped) console.log(`  - ${s}`);
  }
  console.log(`\nSeason: ${SEASON_YEAR} | ${SCHEDULE.filter((g) => g.gameType === 'game').length} official games, ${SCHEDULE.filter((g) => g.gameType === 'scrimmage').length} scrimmages`);
  console.log(`Team: Demo University Baseball (${TEAM_ID})`);
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
