/**
 * render.js — HTML → PNG renderer using Playwright
 *
 * Takes an HTML file (generated by Claude) and renders it to a pixel-perfect
 * PNG at exact Instagram dimensions with 2x retina resolution.
 *
 * Usage:
 *   node render.js <input.html> [output.png] [--width=1080] [--height=1350] [--scale=2]
 *
 * Examples:
 *   node render.js creative.html                          # → creative.png (1080×1350 feed)
 *   node render.js creative.html story.png --height=1920  # → story.png (1080×1920 story)
 *   node render.js creative.html --scale=3                # → 3x retina (3240×4050)
 */

import { chromium } from 'playwright';
import { readFile, writeFile } from 'fs/promises';
import { resolve, basename, extname } from 'path';
import { fileURLToPath } from 'url';

// Instagram dimension presets
const PRESETS = {
  feed:      { width: 1080, height: 1350 },
  story:     { width: 1080, height: 1920 },
  square:    { width: 1080, height: 1080 },
  landscape: { width: 1200, height: 628  },
};

async function render(inputPath, outputPath, options = {}) {
  const {
    width = 1080,
    height = 1350,
    scale = 2,
    preset = null,
    waitMs = 500,
  } = options;

  // Apply preset if specified
  const dims = preset && PRESETS[preset] ? PRESETS[preset] : { width, height };

  const htmlPath = resolve(inputPath);
  const pngPath = outputPath
    ? resolve(outputPath)
    : resolve(basename(inputPath, extname(inputPath)) + '.png');

  console.log(`🎨 Rendering: ${basename(htmlPath)}`);
  console.log(`   Dimensions: ${dims.width}×${dims.height} @ ${scale}x`);
  console.log(`   Output: ${dims.width * scale}×${dims.height * scale}px`);

  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({
    viewport: {
      width: dims.width,
      height: dims.height,
      deviceScaleFactor: scale,
    },
  });

  // Load the HTML file
  const htmlContent = await readFile(htmlPath, 'utf-8');
  await page.setContent(htmlContent, { waitUntil: 'networkidle' });

  // Wait for fonts to load (DM Sans from Google Fonts)
  await page.waitForFunction(() => document.fonts.ready);

  // Extra wait for any CSS animations to settle
  await page.waitForTimeout(waitMs);

  // Capture the full page
  const screenshot = await page.screenshot({
    type: 'png',
    fullPage: false,
    clip: {
      x: 0,
      y: 0,
      width: dims.width,
      height: dims.height,
    },
  });

  await writeFile(pngPath, screenshot);
  await browser.close();

  console.log(`✅ Saved: ${pngPath}`);
  console.log(`   File size: ${(screenshot.length / 1024).toFixed(0)}KB`);

  return pngPath;
}

// Only run CLI when executed directly (not when imported as a module)
const __render_filename = fileURLToPath(import.meta.url);
if (process.argv[1] && resolve(process.argv[1]) === __render_filename) {
  const args = process.argv.slice(2);
  if (args.length === 0) {
    console.log(`
GolfHelm Creative Renderer
──────────────────────────
Usage: node render.js <input.html> [output.png] [options]

Options:
  --width=N      Canvas width (default: 1080)
  --height=N     Canvas height (default: 1350)
  --scale=N      Retina multiplier (default: 2)
  --preset=NAME  Use preset: feed, story, square, landscape
  --wait=N       Wait ms after load (default: 500)

Presets:
  feed      1080×1350  (Instagram feed 4:5)
  story     1080×1920  (Instagram story 9:16)
  square    1080×1080  (Instagram square 1:1)
  landscape 1200×628   (Link preview / OG image)
`);
    process.exit(0);
  }

  const inputFile = args[0];
  const outputFile = args.find(a => !a.startsWith('--') && a !== inputFile);
  const parseArg = (name) => {
    const arg = args.find(a => a.startsWith(`--${name}=`));
    return arg ? arg.split('=')[1] : undefined;
  };

  render(inputFile, outputFile, {
    width: parseInt(parseArg('width') || '1080'),
    height: parseInt(parseArg('height') || '1350'),
    scale: parseInt(parseArg('scale') || '2'),
    preset: parseArg('preset'),
    waitMs: parseInt(parseArg('wait') || '500'),
  }).catch(err => {
    console.error('❌ Render failed:', err.message);
    process.exit(1);
  });
}

export { render, PRESETS };
