// AUTOGENERATED — DO NOT EDIT BY HAND.
//
// Generated by `npm run knowledge:golden-paths-generate`
// (scripts/knowledge/gen-golden-paths.mjs) from
// memory/journeys/golden-paths.yml. A stamp saying so is not evidence this
// file is current — `npm run knowledge:golden-paths-generate:check`
// re-derives it independently and fails on drift.
//
// Compiled to a typed constant so golden-path health never reads
// memory/** at request time — that directory is not in the Vercel function
// bundle. See this generator's own header for why, and for exactly which
// fields were kept (id/name/role/criticality/status, and per stage
// id/feature_id only).

export interface GeneratedGoldenPathStage {
  readonly id: string;
  readonly featureId: string;
}

export interface GeneratedGoldenPath {
  readonly id: string;
  readonly name: string;
  readonly role: 'player' | 'coach';
  readonly criticality: 'high' | 'medium' | 'low';
  readonly status: 'active' | 'collecting';
  readonly stages: readonly GeneratedGoldenPathStage[];
}

export const GOLDEN_PATHS: readonly GeneratedGoldenPath[] = [
  {
    id: "player_login_hub",
    name: "Player logs in and reaches their dashboard",
    role: "player",
    criticality: "high",
    status: "active",
    stages: [
      { id: "authenticate", featureId: "auth_onboarding_join" },
      { id: "land_on_dashboard", featureId: "player_hub" },
    ],
  },
  {
    id: "player_start_round",
    name: "Player configures and starts a new round",
    role: "player",
    criticality: "high",
    status: "active",
    stages: [
      { id: "configure_round", featureId: "golf_round_lifecycle" },
      { id: "start_round", featureId: "golf_round_lifecycle" },
    ],
  },
  {
    id: "player_resume_round",
    name: "Player resumes an in-progress round",
    role: "player",
    criticality: "high",
    status: "active",
    stages: [
      { id: "continue_round", featureId: "golf_round_lifecycle" },
    ],
  },
  {
    id: "player_submit_round",
    name: "Player submits a completed round",
    role: "player",
    criticality: "high",
    status: "collecting",
    stages: [
      { id: "submit_round", featureId: "golf_round_lifecycle" },
    ],
  },
  {
    id: "coach_view_player_stats",
    name: "Coach views team/player stats",
    role: "coach",
    criticality: "medium",
    status: "active",
    stages: [
      { id: "view_team_stats", featureId: "stats_analytics" },
    ],
  },
  {
    id: "coach_view_coachhelm_insight",
    name: "Coach views a CoachHelm AI insight",
    role: "coach",
    criticality: "high",
    status: "active",
    stages: [
      { id: "view_intelligence_hub", featureId: "coach_intelligence_triage" },
    ],
  },
  {
    id: "coach_create_event",
    name: "Coach creates a calendar event",
    role: "coach",
    criticality: "medium",
    status: "collecting",
    stages: [
      { id: "create_event", featureId: "calendar_events" },
    ],
  },
  {
    id: "player_rsvp_event",
    name: "Player RSVPs to a calendar event",
    role: "player",
    criticality: "medium",
    status: "collecting",
    stages: [
      { id: "rsvp_event", featureId: "calendar_events" },
    ],
  },
] as const;
