// DO NOT EDIT — generated by `node replay/runners/gen-coverage-index.mjs`
// from replay/manifests/*.yml + replay/proofs/*.json. See replay/README.md.

export type ReplayVerdict = 'reproduced' | 'inconclusive' | 'not-yet-run';

export interface ReplayCoverageIndexRow {
  replayId: string;
  incidentId: string;
  featureId: string;
  title: string;
  badVersion: string;
  fixedVersion: string;
  verdict: ReplayVerdict;
  ranAt: string | null;
}

export const REPLAY_COVERAGE_INDEX: readonly ReplayCoverageIndexRow[] = [
  {
    replayId: "qualifiers-automatic-completion-2026-08-22",
    incidentId: "memory/incidents/qualifiers/INC-2026-08-22-end-date-closed-qualifier-early.md",
    featureId: "qualifiers",
    title: "The qualifier lifecycle reconciler treated end_date as an automatic player lockout and could mark an active qualifier completed while entrants still had rounds remaining.",
    badVersion: "45a87e70c",
    fixedVersion: "82aaa3bf7c26fe7b956f6310e9f7f18ac6029323",
    verdict: "not-yet-run",
    ranAt: null,
  },
  {
    replayId: "shot-tracking-confirmed-recovery-prompt-2026-08-22",
    incidentId: "memory/incidents/shot_tracking/INC-2026-08-22-confirmed-snapshot-recovery-prompt.md",
    featureId: "shot_tracking",
    title: "A confirmed, server-acknowledged scorecard was shown as an unsaved recovery drawer because a newer local emergency-save timestamp was treated as sufficient evidence of unsaved progress on its own.",
    badVersion: "4fba16c63",
    fixedVersion: "48b41e1c4d8c86f12f5a2becd11454f5bd3899e2",
    verdict: "not-yet-run",
    ranAt: null,
  },
  {
    replayId: "shot-tracking-stale-delete-2026-08-22",
    incidentId: "memory/incidents/shot_tracking/INC-2026-08-22-delete-shot-stale-id.md",
    featureId: "shot_tracking",
    title: "Overlapping Undo and Edit Shot could act on the same local history; a delete whose row was already absent had no stable reconciliation contract.",
    badVersion: "d5b9368d1",
    fixedVersion: "5eececafc930c1d10718371bd2954c9ec32e758c",
    verdict: "not-yet-run",
    ranAt: null,
  },
];
