-- Adds an AI-generated editorial recap to each completed round.
-- A 2-sentence summary in the brand voice, generated once when the
-- round transitions to completed (or lazily on first detail-view).
-- Persisted so we don't regenerate on every read.
ALTER TABLE golf_rounds
  ADD COLUMN IF NOT EXISTS ai_recap text,
  ADD COLUMN IF NOT EXISTS ai_recap_generated_at timestamptz;

COMMENT ON COLUMN golf_rounds.ai_recap IS
  'Two-sentence editorial recap of the round, generated by Vercel AI Gateway / Claude when the round completes. Brand voice — magazine-style beat-reporter recap.';
