-- Auto-save partial-round UPDATE regression fix.
--
-- savePartialRound() (src/app/golf/actions/golf.ts) builds a roundData
-- object that includes player_id, team_id, qualifier_id, and
-- qualifier_round_number, then calls
--   supabase.from('golf_rounds').update(roundData) ...
-- on the existing in_progress row.
--
-- The baseline grants on golf_rounds (see 20260527000000_prod_public_baseline.sql)
-- gave `authenticated` SELECT/INSERT/DELETE on the table plus column-
-- level UPDATE on the user-controlled scoring/course columns. The four
-- identity-shaped columns above were NOT in that list, so Postgres'
-- per-column UPDATE-privilege check (which runs regardless of whether
-- the SET value differs from the current value) failed every auto-save
-- tick with
--   ERROR 42501: permission denied for table golf_rounds
-- → "Auto-save server error: Failed to save round. Please try again."
-- in the round-tracking UI, repeatedly tripping the client-side
-- circuit breaker.
--
-- Same root cause was fixed for golf_round_reviews in
-- 20260602190000_grant_update_round_reviews_authenticated.sql and for
-- golf_coach_insights in 20260528011000_harden_coach_insights_update_grants.sql,
-- both of which went table-wide. This migration is more conservative —
-- it preserves the baseline's intentional column-allowlist by only
-- adding the four identity columns the auto-save payload actually
-- needs. Column-level GRANT UPDATE is additive in Postgres, so the
-- 25+ existing column grants stay in effect.
--
-- RLS remains the row-level guard — `golf_rounds_player_update`
-- (player updates own rounds) and the coach/team policies continue to
-- scope WHICH rows the authenticated role can touch. This GRANT only
-- changes WHICH columns the role can SET.
--
-- Idempotent: re-running GRANT is a no-op in Postgres.
GRANT UPDATE (player_id, team_id, qualifier_id, qualifier_round_number)
ON TABLE public.golf_rounds TO authenticated;
