-- Update the insight_type CHECK constraint to include V2 CoachHelm insight types
-- This allows the new insight types generated by the V2 intelligence engine

-- First drop the existing constraint
ALTER TABLE golf_coach_insights
DROP CONSTRAINT IF EXISTS golf_coach_insights_insight_type_check;

-- Add new constraint with all valid types (original + V2)
ALTER TABLE golf_coach_insights
ADD CONSTRAINT golf_coach_insights_insight_type_check CHECK (insight_type IN (
  -- Original types (from migration 039)
  'performance_decline', 'performance_improvement', 'pattern_detected',
  'practice_recommendation', 'roster_alert', 'qualifying_watch',
  'attendance_concern', 'milestone_reached', 'comparison_insight',
  -- V2 CoachHelm types (from @/lib/coachhelm/insight-types.ts)
  'scoring_decline', 'stat_regression', 'tournament_pressure',
  'plateau', 'bubble_player', 'surge_player', 'streak',
  'recurring_weakness', 'closing_holes', 'par_3_issues',
  'team_trend', 'roster_recommendation'
));
