/**
 * Generated cross-links for the Clubhouse docs (written by `registry.mjs sync`,
 * checked for drift by `clubhouse:check`):
 *   - the "Related" block in each page's PAGE.md: its manifest, the other page
 *     docs, catalog, checklist, phone spec, design boards, code, held plans,
 *     audits that name it, and its PROGRESS row;
 *   - docs/clubhouse/AUDITS.md, from config/clubhouse/audits.json: every audit,
 *     plan and inventory doc with its date, scope, status and the pages it touches.
 */
import { posix } from 'node:path';

export const AUDIT_KINDS = ['audit', 'plan', 'inventory'];
export const AUDIT_STATUSES = ['planned', 'in_progress', 'done', 'superseded'];
export const RELATED_START = '<!-- clubhouse:related:start (generated by node scripts/clubhouse/registry.mjs sync; do not edit) -->';
export const RELATED_END = '<!-- clubhouse:related:end -->';
const DOC_FILES = ['PAGE', 'DESIGN', 'CONTRACT', 'WIRING', 'VERIFY', 'CHANGELOG'];

const cell = (s) => String(s ?? '').replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const pageDir = (m) => `docs/clubhouse/pages/${m.id}-${m.slug}`;
const link = (from, to, text) => `[${text ?? to.split('/').pop()}](${encodeURI(posix.relative(posix.dirname(from), to))})`;

/** Audits that name this page explicitly (an all-page audit is linked once, through AUDITS.md). */
export const auditsFor = (audits, m) => audits.filter((a) => (a.pages ?? []).includes(m.id));

export function renderRelatedBlock({ m, audits, exists }) {
  const from = `${pageDir(m)}/PAGE.md`;
  const row = (label, cells) => (cells.length ? `| ${label} | ${cells.join(' · ')} |\n` : '');
  const code = [m.implementation?.root, m.implementation?.loader, m.implementation?.route, m.implementation?.styles].filter(Boolean);
  const named = auditsFor(audits, m).map((a) => link(from, `docs/clubhouse/${a.file}`, a.file.replace(/\.md$/, '')));
  if (audits.some((a) => a.allPages)) named.push(link(from, 'docs/clubhouse/AUDITS.md', 'all audits'));
  let out = `${RELATED_START}\n## Related\n\n| | |\n| --- | --- |\n`;
  out += row('Manifest', [link(from, `config/clubhouse/pages/${m.id}-${m.slug}.json`)]);
  out += row('Page docs', DOC_FILES.map((d) => link(from, `${pageDir(m)}/${d}.md`, d)));
  const doc = (p) => (p && exists(p) ? [link(from, p, p.replace('docs/clubhouse/', ''))] : []);
  out += row('State catalog', doc(m.catalog));
  out += row('Checklist', doc(m.checklist));
  out += row('Phone spec', doc(m.phoneSpec));
  out += row('Design boards', [...(m.design?.desktop ?? []), ...(m.design?.phone ?? [])].filter(exists).map((p) => link(from, p)));
  out += row('Code', code.filter(exists).map((p) => link(from, p)));
  out += row('Held plans', (m.held ?? []).filter(exists).map((p) => link(from, p)));
  out += row('Audits', named);
  out += row('Tracker', [`${link(from, 'docs/clubhouse/PROGRESS.md', 'PROGRESS.md')}, row "${cell(m.progressRow ?? m.name)}"`]);
  out += row('Screenshots', [`${link(from, `${pageDir(m)}/VERIFY.md#screenshots`, 'VERIFY.md, Screenshots')}`]);
  return `${out}${RELATED_END}`;
}

/** PAGE.md with its Related block replaced, or inserted under the title when it has none. */
export function renderRelated({ m, audits, exists, existing }) {
  const block = renderRelatedBlock({ m, audits, exists });
  const start = existing.indexOf(RELATED_START);
  const end = existing.indexOf(RELATED_END);
  if (start >= 0 && end > start) return existing.slice(0, start) + block + existing.slice(end + RELATED_END.length);
  const lines = existing.split('\n');
  const title = lines.findIndex((l) => l.startsWith('# '));
  lines.splice(title + 1, 0, '', block);
  return lines.join('\n');
}

export function renderAudits({ audits, manifests, head }) {
  const byId = new Map(manifests.map((m) => [m.id, m]));
  const pagesCell = (a) => {
    const links = (a.pages ?? []).filter((id) => byId.has(id)).map((id) => `[${id}](pages/${id}-${byId.get(id).slug}/PAGE.md)`);
    return a.allPages ? `all${links.length ? ` (detail: ${links.join(', ')})` : ''}` : links.join(', ');
  };
  let out = head('Clubhouse audits and plans', 'Every audit, plan and inventory doc in `docs/clubhouse/`: when, what it covers, where it stands and which pages it touches. The owner decisions behind them are in [`PROGRESS.md`](PROGRESS.md); the screenshot evidence is in each page\'s VERIFY.md "Screenshots" table. A new audit doc is registered in `config/clubhouse/audits.json`, then `node scripts/clubhouse/registry.mjs sync`.');
  out += '\n| Doc | Kind | Date | Scope | Status | Pages |\n| --- | --- | --- | --- | --- | --- |\n';
  for (const a of [...audits].sort((x, y) => y.date.localeCompare(x.date) || x.file.localeCompare(y.file))) {
    out += `| [${cell(a.title ?? a.file)}](${encodeURI(a.file)}) | ${a.kind} | ${a.date} | ${cell(a.scope)} | ${a.status.replace('_', ' ')}${a.note ? `: ${cell(a.note)}` : ''} | ${pagesCell(a)} |\n`;
  }
  return out;
}

/** Violations for config/clubhouse/audits.json and the docs that must link the index. */
export function checkAudits({ audits, manifests, exists, docs, readmeMd, progressMd }) {
  const v = [];
  const ids = new Set(manifests.map((m) => m.id));
  const seen = new Set();
  for (const a of audits) {
    const at = `config/clubhouse/audits.json ${a.file ?? '(entry)'}`;
    if (!a.file || !/^[A-Za-z0-9_.-]+\.md$/.test(a.file)) v.push(`${at}: file must be a docs/clubhouse/*.md name`);
    else if (seen.has(a.file)) v.push(`${at}: listed twice`);
    else if (!exists(`docs/clubhouse/${a.file}`)) v.push(`${at}: docs/clubhouse/${a.file} does not exist`);
    seen.add(a.file);
    if (!AUDIT_KINDS.includes(a.kind)) v.push(`${at}: kind "${a.kind}" is not one of ${AUDIT_KINDS.join(', ')}`);
    if (!AUDIT_STATUSES.includes(a.status)) v.push(`${at}: status "${a.status}" is not one of ${AUDIT_STATUSES.join(', ')}`);
    if (!/^\d{4}-\d{2}-\d{2}$/.test(a.date ?? '')) v.push(`${at}: date must be YYYY-MM-DD`);
    if (!a.scope) v.push(`${at}: scope is empty`);
    if (!a.title) v.push(`${at}: title is empty`);
    if (!a.allPages && !(a.pages ?? []).length) v.push(`${at}: names no page (set allPages or pages)`);
    for (const id of a.pages ?? []) if (!ids.has(id)) v.push(`${at}: page ${id} is not a registered page`);
  }
  for (const d of docs.filter((n) => /AUDIT|_PLAN\.md$/.test(n) && n !== 'AUDITS.md')) {
    if (!seen.has(d)) v.push(`docs/clubhouse/${d}: an audit or plan doc that config/clubhouse/audits.json does not list (add it, then run registry.mjs sync)`);
  }
  if (!/\]\(AUDITS\.md\)/.test(readmeMd)) v.push('docs/clubhouse/README.md does not link AUDITS.md');
  if (!/\]\(AUDITS\.md\)/.test(progressMd)) v.push('docs/clubhouse/PROGRESS.md does not link AUDITS.md');
  return v;
}
