// The authority map must point at documents that exist, are current, and say
// where they came from.
//
// Two of these tests exist because the checker's FIRST version failed on the
// sentences that had just fixed the problem. `docs/README.md` explains that a
// Start Here entry "used to point at" a superseded ledger; the checker matched
// any backticked .md inside the section and read that explanation as a pointer.
// The same shape appeared in the HELM_OS table, where `docs.feature` is a field
// name, not a path. A substring is not a mechanism — the third time this repo
// has paid for that, and the reason the matchers below are structural: a Start
// Here entry is the BOLDED LEAD of a list item, and a path contains a slash.
//
// The other reason for this file: the checker must never fail on prose. A
// document containing the word "canonical" is a prompt for a human, not a
// contradiction, and 171 tracked documents contain authority language today.

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { spawnSync, execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync, realpathSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

const SCRIPT = resolve(__dirname, '../../../scripts/knowledge/check-authority.mjs');

const HELM_OS = [
  '# Helm OS',
  '',
  '| Question | Authority |',
  '| --- | --- |',
  '| What files belong to a feature? | `memory/registry.yml` |',
  '| How does that feature behave now? | the `docs.feature` it maps to |',
  '| How does self-heal operate? | `docs/ai-system/selfheal/` |',
  '| What is enforced? | `docs/ENFORCEMENT.md` |',
  '',
].join('\n');

const README = [
  '# docs',
  '',
  '## Start here',
  '',
  '- **`memory/registry.yml`** — the router.',
  '',
  '## `docs/archive/<YYYY-MM>/`',
  '',
].join('\n');

describe('authority integrity', () => {
  let root: string;

  function write(rel: string, body: string) {
    const p = join(root, rel);
    mkdirSync(join(p, '..'), { recursive: true });
    writeFileSync(p, body);
  }

  function commitAll() {
    execFileSync('git', ['add', '-A'], { cwd: root, stdio: 'ignore' });
  }

  function run() {
    commitAll();
    return spawnSync(process.execPath, [SCRIPT], {
      cwd: root,
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'pipe'],
    });
  }

  beforeEach(() => {
    root = realpathSync(mkdtempSync(join(tmpdir(), 'helm-authority-')));
    execFileSync('git', ['init', '-q'], { cwd: root });
    execFileSync('git', ['config', 'user.email', 't@e.com'], { cwd: root });
    execFileSync('git', ['config', 'user.name', 'T'], { cwd: root });
    write('docs/HELM_OS.md', HELM_OS);
    write('docs/README.md', README);
    write('memory/registry.yml', 'version: 1\n\nfeatures:\n  qualifiers:\n    docs:\n      feature: memory/features/qualifiers.md\n');
    write('memory/features/qualifiers.md', '# Qualifiers\n');
    write('docs/ai-system/selfheal/README.md', '# selfheal\n');
    write('docs/ENFORCEMENT.md', '# enforcement\n');
    mkdirSync(join(root, 'docs/generated'), { recursive: true });
    write('docs/generated/X.md', '<!-- GENERATED by scripts/gen-x.mjs -->\n# X\n');
    write('scripts/gen-x.mjs', '// gen\n');
  });

  afterEach(() => {
    try {
      rmSync(root, { recursive: true, force: true });
    } catch {
      /* best effort */
    }
  });

  it('passes a map whose every authority resolves and is current', () => {
    const r = run();
    expect(r.status).toBe(0);
    expect(r.stdout).toMatch(/Every current authority resolves/);
  });

  it('does NOT treat a backticked field name as a path', () => {
    // `docs.feature` names a registry FIELD. The first version of this checker
    // reported it as a dead authority.
    expect(run().stderr).not.toMatch(/docs\.feature/);
  });

  it('accepts a directory authority written with a trailing slash', () => {
    expect(run().status).toBe(0);
  });

  it('refuses a map row pointing at a file that is not tracked', () => {
    write('docs/HELM_OS.md', HELM_OS.replace('`memory/registry.yml`', '`memory/gone.yml`'));
    expect(run().stderr).toMatch(/HELM_OS_DEAD_AUTHORITY/);
  });

  it('refuses a map row pointing at a document whose header says SUPERSEDED', () => {
    write('docs/ENFORCEMENT.md', '<!--\nSTATUS: SUPERSEDED\nSUPERSEDED BY / WHY: x\n-->\n# e\n');
    expect(run().stderr).toMatch(/HELM_OS_RETIRED_AUTHORITY/);
  });

  it('refuses a registry route to a retired document', () => {
    write('memory/features/qualifiers.md', '<!--\nSTATUS: SUPERSEDED\nSUPERSEDED BY / WHY: y\n-->\n# q\n');
    expect(run().stderr).toMatch(/REGISTRY_RETIRED_ROUTE/);
  });

  it('names EVERY route to a retired document, not just the last one', () => {
    // A Map keyed by path with a single value hid a second route: one document
    // was reachable from two features and fixing the reported one left the
    // other in place, so the checker failed again on what looked identical.
    write(
      'memory/registry.yml',
      [
        'version: 1',
        '',
        'features:',
        '  qualifiers:',
        '    docs:',
        '      feature: memory/features/qualifiers.md',
        '  shot_tracking:',
        '    docs:',
        '      feature: memory/features/qualifiers.md',
        '',
      ].join('\n'),
    );
    write('memory/features/qualifiers.md', '<!--\nSTATUS: SUPERSEDED\nSUPERSEDED BY / WHY: y\n-->\n# q\n');
    const err = run().stderr;
    expect(err).toMatch(/qualifiers\.docs\.feature/);
    expect(err).toMatch(/shot_tracking\.docs\.feature/);
  });

  it('refuses a generated document that names no generator', () => {
    write('docs/generated/X.md', '# X\n');
    expect(run().stderr).toMatch(/GENERATED_WITHOUT_GENERATOR/);
  });

  it('refuses a generated document whose generator is not tracked', () => {
    write('docs/generated/X.md', '<!-- GENERATED by scripts/gone.mjs -->\n# X\n');
    expect(run().stderr).toMatch(/GENERATED_DEAD_GENERATOR/);
  });

  it('refuses a retired document that names no replacement', () => {
    write('docs/orphan.md', '<!--\nSTATUS: SUPERSEDED\n-->\n# orphan\n');
    expect(run().stderr).toMatch(/RETIRED_WITHOUT_REPLACEMENT/);
  });

  it('refuses a Start Here ENTRY that points at a retired document', () => {
    write('docs/old.md', '<!--\nSTATUS: SUPERSEDED\nSUPERSEDED BY / WHY: z\n-->\n# old\n');
    write('docs/README.md', README.replace('- **`memory/registry.yml`** — the router.', '- **`docs/old.md`** — the ledger.'));
    expect(run().stderr).toMatch(/START_HERE_RETIRED/);
  });

  it('does NOT fail on prose ABOUT a retired document', () => {
    // The sentence that fixed the problem must not be what breaks the check.
    write('docs/old.md', '<!--\nSTATUS: SUPERSEDED\nSUPERSEDED BY / WHY: z\n-->\n# old\n');
    write(
      'docs/README.md',
      README.replace(
        '- **`memory/registry.yml`** — the router.',
        '- **`memory/registry.yml`** — the router. This entry used to point at\n  `docs/old.md`, whose header now reads SUPERSEDED.',
      ),
    );
    expect(run().status).toBe(0);
  });

  it('REPORTS authority language and never fails on it', () => {
    write('docs/loud.md', '# loud\n\nThis is the canonical source of truth, authoritative in every way.\n');
    const r = run();
    expect(r.status).toBe(0);
    expect(r.stdout).toMatch(/document\(s\) using authority language/);
  });
});
