import Foundation
import Capacitor
import CoreHaptics

/// Helm's Core Haptics signature patterns (premium plan §22) — the rare,
/// designed moments the stock UIFeedbackGenerator vocabulary can't express.
/// Exposed to the web layer as the `HelmHaptics` Capacitor plugin, gated
/// there by `hasNativeCapability('coreHapticsV1')` (build ≥ 10).
///
/// Contract with the web layer:
/// - `play({ pattern })` never rejects for sensory reasons: on hardware
///   without haptics (or any engine failure) it resolves `{ played: false }`
///   and the caller falls back to the UIFeedbackGenerator grammar.
/// - Patterns are short (≤ 0.4 s), transient-only, event-driven — never
///   continuous background work (plan §43).
/// - The user's in-app haptics preference is enforced on the WEB side at the
///   shared `triggerHaptic`/`fwHaptic` gate; this plugin is dumb on purpose.
///
/// Registered in `GolfBridgeViewController.capacitorDidLoad()` — app-local
/// plugin, no pod/SPM packaging (CapApp-SPM's manifest is CLI-managed and
/// regenerated by `cap sync`, so it cannot host first-party targets).
@objc(HelmHapticsPlugin)
public class HelmHapticsPlugin: CAPPlugin, CAPBridgedPlugin {
    public let identifier = "HelmHapticsPlugin"
    public let jsName = "HelmHaptics"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "isAvailable", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "play", returnType: CAPPluginReturnPromise),
    ]

    private var engine: CHHapticEngine?

    private var supportsHaptics: Bool {
        CHHapticEngine.capabilitiesForHardware().supportsHaptics
    }

    @objc func isAvailable(_ call: CAPPluginCall) {
        call.resolve(["available": supportsHaptics])
    }

    @objc func play(_ call: CAPPluginCall) {
        guard supportsHaptics else {
            call.resolve(["played": false])
            return
        }
        guard let name = call.getString("pattern"),
              let events = Self.patterns[name] else {
            call.reject("Unknown pattern")
            return
        }
        do {
            let engine = try readyEngine()
            let pattern = try CHHapticPattern(events: events, parameters: [])
            let player = try engine.makePlayer(with: pattern)
            try player.start(atTime: CHHapticTimeImmediate)
            call.resolve(["played": true])
        } catch {
            // Sensory failure is never a product failure — the web layer
            // falls back to the UIFeedbackGenerator grammar.
            call.resolve(["played": false])
        }
    }

    /// Lazily create and start the engine, recovering from resets. The
    /// engine is released by the system opportunistically; `resetHandler`
    /// and a nil-out on stop make the next `play` self-heal (§22: handle
    /// engine reset/interruption, never block UI).
    private func readyEngine() throws -> CHHapticEngine {
        if let engine { return engine }
        let created = try CHHapticEngine()
        created.playsHapticsOnly = true
        created.resetHandler = { [weak self] in
            self?.engine = nil
        }
        created.stoppedHandler = { [weak self] _ in
            self?.engine = nil
        }
        try created.start()
        engine = created
        return created
    }

    // MARK: - Signature patterns (§22 — tuned on hardware, kept subtle)

    private static func transient(_ t: TimeInterval, intensity: Float, sharpness: Float) -> CHHapticEvent {
        CHHapticEvent(
            eventType: .hapticTransient,
            parameters: [
                CHHapticEventParameter(parameterID: .hapticIntensity, value: intensity),
                CHHapticEventParameter(parameterID: .hapticSharpness, value: sharpness),
            ],
            relativeTime: t
        )
    }

    /// helmCommit — "subtle transient → slightly firmer landing".
    /// helmReject — a soft descending pair; clearly not-success, never alarming.
    /// helmMilestone — a rare, short three-step lift (§19: milestones feel
    /// special precisely because the app does not celebrate everything).
    private static let patterns: [String: [CHHapticEvent]] = [
        "helmCommit": [
            transient(0.0, intensity: 0.45, sharpness: 0.40),
            transient(0.09, intensity: 0.80, sharpness: 0.60),
        ],
        "helmReject": [
            transient(0.0, intensity: 0.60, sharpness: 0.30),
            transient(0.12, intensity: 0.35, sharpness: 0.20),
        ],
        "helmMilestone": [
            transient(0.0, intensity: 0.45, sharpness: 0.45),
            transient(0.11, intensity: 0.65, sharpness: 0.55),
            transient(0.24, intensity: 0.90, sharpness: 0.65),
        ],
    ]
}
